In [4]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np
import optuna
import joblib
import warnings
warnings.filterwarnings("ignore")
import pickle
import pandas as pd
from sklearn.metrics import roc_auc_score, log_loss, brier_score_loss, accuracy_score

In [5]:
splits = joblib.load("splits/8_windows_all_features_knn.pkl")

In [6]:
splits[0]['X_train_raw'].shape

(1380, 1065)

In [7]:
from sklearn.impute import KNNImputer, SimpleImputer

feature_names = splits[0]["X_train_raw"].columns

for split in splits:

    # imputer = SimpleImputer(strategy="median")
    imputer = KNNImputer(n_neighbors=5, weights="uniform", metric="nan_euclidean")

    split["X_train_raw"] = pd.DataFrame(imputer.fit_transform(split["X_train_raw"]), columns=feature_names)
    split["X_val_raw"] = pd.DataFrame(imputer.transform(split["X_val_raw"]), columns=feature_names)
    split["X_test_raw"] = pd.DataFrame(imputer.transform(split["X_test_raw"]), columns=feature_names)

    vlr_match_id_train = split["X_train_raw"]["vlr_match_id"]
    vlr_match_id_val = split["X_val_raw"]["vlr_match_id"]
    vlr_match_id_test = split["X_test_raw"]["vlr_match_id"]

    split["X_train_raw"] = split["X_train_raw"].loc[:, split["X_train_raw"].columns.str.startswith('delta_')]
    split["X_val_raw"] = split["X_val_raw"].loc[:, split["X_val_raw"].columns.str.startswith('delta_')]
    split["X_test_raw"] = split["X_test_raw"].loc[:, split["X_test_raw"].columns.str.startswith('delta_')]

    split["X_train_raw"]["vlr_match_id"] = vlr_match_id_train
    split["X_val_raw"]["vlr_match_id"] = vlr_match_id_val
    split["X_test_raw"]["vlr_match_id"] = vlr_match_id_test

In [8]:
splits[0]['X_train_raw'].shape

(1380, 355)

In [9]:
def bootstrap_logloss_ci(y_true, y_proba, n_boot=2000, ci=0.95, seed=0):
    rng = np.random.default_rng(seed)
    y_true = np.asarray(y_true)
    y_proba = np.asarray(y_proba)
    n = len(y_true)
    scores = np.empty(n_boot)
    for i in range(n_boot):
        idx = rng.integers(0, n, n)
        scores[i] = log_loss(y_true[idx], y_proba[idx])
    lo, hi = np.percentile(scores, [(1 - ci) / 2 * 100, (1 + ci) / 2 * 100])
    return scores.mean(), lo, hi

In [10]:
# def make_objective(X_train, y_train, X_val, y_val):
#     def objective(trial):
#         C = trial.suggest_float('C', 1e-3, 100, log=True)
#         l1_ratio = trial.suggest_float('l1_ratio', 0.0, 1)

#         all_val_true, all_val_proba = [], []

#         scaler = StandardScaler()
#         X_train_scaled = scaler.fit_transform(X_train)
#         X_val_scaled   = scaler.transform(X_val)

#         selector = VarianceThreshold(threshold=0.01)
#         X_train_sel = selector.fit_transform(X_train_scaled)
#         X_val_sel   = selector.transform(X_val_scaled)

#         model = LogisticRegression(C=C, l1_ratio=l1_ratio, solver='saga', max_iter=5000)
#         model.fit(X_train_sel, y_train)

#         val_proba = model.predict_proba(X_val_sel)[:, 1]
#         all_val_true.append(y_val); all_val_proba.append(val_proba)
#         logloss = log_loss(all_val_true, all_val_proba)
#         return logloss

#     return objective

In [11]:
from sklearn.model_selection import StratifiedKFold

def make_objective(X_train, y_train, n_inner_folds=5, seed=0):
    def objective(trial):
        C = trial.suggest_float('C', 1e-3, 10, log=True)
        l1_ratio = trial.suggest_float('l1_ratio', 0.0, 1.0)

        skf = StratifiedKFold(n_splits=n_inner_folds, shuffle=True, random_state=seed)
        fold_losses = []

        for train_idx, inner_val_idx in skf.split(X_train, y_train):
            X_fold_train, X_fold_val = X_train[train_idx], X_train[inner_val_idx]

            scaler = StandardScaler()
            X_fold_train_scaled = scaler.fit_transform(X_fold_train)
            X_fold_val_scaled = scaler.transform(X_fold_val)

            selector = VarianceThreshold(threshold=0.01)
            X_fold_train_sel = selector.fit_transform(X_fold_train_scaled)
            X_fold_val_sel = selector.transform(X_fold_val_scaled)

            model = LogisticRegression(C=C, l1_ratio=l1_ratio, solver="saga", max_iter=5000)
            model.fit(X_fold_train_sel, y_train[train_idx])
            proba = model.predict_proba(X_fold_val_sel)[:, 1]
            fold_losses.append(log_loss(y_train[inner_val_idx], proba, labels=[0, 1]))

        return np.mean(fold_losses)

    return objective

In [12]:
# features = []
# parameters = []

# for split in splits:
#     X_train, y_train, X_val, y_val = split["X_train_raw"], split["y_train"], split["X_val_raw"], split["y_val"]

#     scaler = StandardScaler()
#     X_train_scaled = scaler.fit_transform(X_train)
#     X_val_scaled   = scaler.transform(X_val)

#     selector = VarianceThreshold(threshold=0.01)
#     X_train_sel = selector.fit_transform(X_train_scaled)
#     X_val_sel   = selector.transform(X_val_scaled)

#     model = LogisticRegression(solver='saga', max_iter=5000)
#     model.fit(X_train_sel, y_train)

#     feature_name_coef = list(zip(X_train.columns, model.coef_[0]))
#     feature_name_coef.sort(key=lambda x: abs(x[1]), reverse=True)
#     features.append([name for name, coef in feature_name_coef[:30]])

In [13]:
features = []

for split in splits:
    X_train, y_train, X_val, y_val = split["X_train_raw"], split["y_train"], split["X_val_raw"], split["y_val"]

    # objective = make_objective(X_train, y_train, X_val, y_val)
    objective = make_objective(X_train.values, y_train.values)
    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=100, n_jobs=-1)
    params = study.best_params

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled   = scaler.transform(X_val)

    selector = VarianceThreshold(threshold=0.01)
    X_train_sel = selector.fit_transform(X_train_scaled)
    X_val_sel   = selector.transform(X_val_scaled)

    model = LogisticRegression(C=params['C'], l1_ratio=params['l1_ratio'], solver='saga', max_iter=5000)
    model.fit(X_train_sel, y_train)

    feature_name_coef = list(zip(X_train.columns, model.coef_[0]))
    feature_name_coef.sort(key=lambda x: abs(x[1]), reverse=True)
    features.append([name for name, coef in feature_name_coef[:30]])

[I 2026-09-10 15:01:54,947] A new study created in memory with name: no-name-93ac959c-281b-4d5a-93b9-598d4f7fd5ba
[I 2026-09-10 15:01:57,145] Trial 10 finished with value: 0.6794841461806914 and parameters: {'C': 0.0027379569747386966, 'l1_ratio': 0.32632800258806227}. Best is trial 10 with value: 0.6794841461806914.
[I 2026-09-10 15:01:58,286] Trial 12 finished with value: 0.5692368399026602 and parameters: {'C': 0.014031212646171659, 'l1_ratio': 0.06927700031698902}. Best is trial 12 with value: 0.5692368399026602.
[I 2026-09-10 15:01:58,756] Trial 0 finished with value: 0.6488886469092723 and parameters: {'C': 0.010430530861113027, 'l1_ratio': 0.5583695315268911}. Best is trial 12 with value: 0.5692368399026602.
[I 2026-09-10 15:01:59,834] Trial 15 finished with value: 0.6589610322596698 and parameters: {'C': 0.012973114642251605, 'l1_ratio': 0.9277414361594682}. Best is trial 12 with value: 0.5692368399026602.
[I 2026-09-10 15:02:00,869] Trial 9 finished with value: 0.6554411987575468 and parameters: {'C': 0.012941720152233034, 'l1_ratio': 0.8251496173368941}. Best is trial 12 with value: 0.5692368399026602.
[I 2026-09-10 15:02:02,187] Trial 6 finished with value: 0.5571859085582774 and parameters: {'C': 0.04619855158207534, 'l1_ratio': 0.33274536034517055}. Best is trial 6 with value: 0.5571859085582774.
[I 2026-09-10 15:02:02,563] Trial 21 finished with value: 0.6931159713059204 and parameters: {'C': 0.001402741658577936, 'l1_ratio': 0.5869225392114419}. Best is trial 6 with value: 0.5571859085582774.
[I 2026-09-10 15:02:06,287] Trial 19 finished with value: 0.6184558062389528 and parameters: {'C': 0.035338943004855274, 'l1_ratio': 0.7728053549806111}. Best is trial 6 with value: 0.5571859085582774.
[I 2026-09-10 15:02:07,017] Trial 17 finished with value: 0.5729453983662416 and parameters: {'C': 0.06004309169015293, 'l1_ratio': 0.6439040077533906}. Best is trial 6 with value: 0.5571859085582774.
[I 2026-09-10 15:02:16,423] Trial 8 finished with value: 0.5416049519254708 and parameters: {'C': 0.1241891629203373, 'l1_ratio': 0.8731234180257706}. Best is trial 8 with value: 0.5416049519254708.
[I 2026-09-10 15:02:17,336] Trial 16 finished with value: 0.4546680136835498 and parameters: {'C': 0.17534443858549115, 'l1_ratio': 0.22624187229558645}. Best is trial 16 with value: 0.4546680136835498.
[I 2026-09-10 15:02:25,851] Trial 2 finished with value: 0.5300247508479399 and parameters: {'C': 0.15856697960241667, 'l1_ratio': 0.9757151768343576}. Best is trial 16 with value: 0.4546680136835498.
[I 2026-09-10 15:02:37,276] Trial 11 finished with value: 0.37701834860015226 and parameters: {'C': 0.6818557174636319, 'l1_ratio': 0.501465843594033}. Best is trial 11 with value: 0.37701834860015226.
[I 2026-09-10 15:02:49,897] Trial 24 finished with value: 0.4173283698394945 and parameters: {'C': 0.482567491753512, 'l1_ratio': 0.7850854818449182}. Best is trial 11 with value: 0.37701834860015226.
[I 2026-09-10 15:02:50,755] Trial 20 finished with value: 0.4572389820001594 and parameters: {'C': 0.35173466475489573, 'l1_ratio': 0.9237602461730264}. Best is trial 11 with value: 0.37701834860015226.
[I 2026-09-10 15:03:02,229] Trial 14 finished with value: 0.30388954953320346 and parameters: {'C': 1.8014034559323848, 'l1_ratio': 0.4567010309670939}. Best is trial 14 with value: 0.30388954953320346.
[I 2026-09-10 15:03:04,943] Trial 25 finished with value: 0.31736466117935197 and parameters: {'C': 1.459729841084318, 'l1_ratio': 0.016871797495527918}. Best is trial 14 with value: 0.30388954953320346.
[I 2026-09-10 15:03:06,903] Trial 26 finished with value: 0.33215624703509966 and parameters: {'C': 1.1276232382242115, 'l1_ratio': 0.022346776335125357}. Best is trial 14 with value: 0.30388954953320346.
[I 2026-09-10 15:03:11,397] Trial 3 finished with value: 0.273626691887295 and parameters: {'C': 3.0855761171334493, 'l1_ratio': 0.12852312313027836}. Best is trial 3 with value: 0.273626691887295.
[I 2026-09-10 15:03:19,191] Trial 18 finished with value: 0.3160091790853131 and parameters: {'C': 1.5140210741790932, 'l1_ratio': 0.9492885604922634}. Best is trial 3 with value: 0.273626691887295.
[I 2026-09-10 15:03:27,031] Trial 27 finished with value: 0.3209464737503963 and parameters: {'C': 1.3748840606577617, 'l1_ratio': 0.049368301250322044}. Best is trial 3 with value: 0.273626691887295.
[I 2026-09-10 15:03:28,968] Trial 22 finished with value: 0.2588108651278809 and parameters: {'C': 4.2642198460061875, 'l1_ratio': 0.07306573641294167}. Best is trial 22 with value: 0.2588108651278809.
[I 2026-09-10 15:03:31,537] Trial 28 finished with value: 0.3234611164752422 and parameters: {'C': 1.356224815657983, 'l1_ratio': 0.30317963172722795}. Best is trial 22 with value: 0.2588108651278809.
[I 2026-09-10 15:03:32,187] Trial 23 finished with value: 0.26089111175690255 and parameters: {'C': 3.5029615089585513, 'l1_ratio': 0.4398229256727697}. Best is trial 22 with value: 0.2588108651278809.
[I 2026-09-10 15:03:34,370] Trial 4 finished with value: 0.24198320126944717 and parameters: {'C': 6.423927827077506, 'l1_ratio': 0.20215823330771}. Best is trial 4 with value: 0.24198320126944717.
[I 2026-09-10 15:03:40,270] Trial 7 finished with value: 0.24136074793423773 and parameters: {'C': 5.9859456861250555, 'l1_ratio': 0.35212929592631903}. Best is trial 7 with value: 0.24136074793423773.
[I 2026-09-10 15:03:42,223] Trial 13 finished with value: 0.2459538605814723 and parameters: {'C': 4.066063462458743, 'l1_ratio': 0.7151112654971561}. Best is trial 7 with value: 0.24136074793423773.
[I 2026-09-10 15:03:44,540] Trial 5 finished with value: 0.23901927964648556 and parameters: {'C': 6.440413298051276, 'l1_ratio': 0.3784930181715839}. Best is trial 5 with value: 0.23901927964648556.
[I 2026-09-10 15:03:49,096] Trial 29 finished with value: 0.3083287178443686 and parameters: {'C': 1.6959039968089002, 'l1_ratio': 0.46134567450155783}. Best is trial 5 with value: 0.23901927964648556.
[I 2026-09-10 15:03:57,244] Trial 1 finished with value: 0.24779876682575636 and parameters: {'C': 5.896096479027878, 'l1_ratio': 0.013849027153009508}. Best is trial 5 with value: 0.23901927964648556.
[I 2026-09-10 15:04:31,443] Trial 31 finished with value: 0.26609795058627284 and parameters: {'C': 3.1872117978703507, 'l1_ratio': 0.44683684634225057}. Best is trial 5 with value: 0.23901927964648556.
[I 2026-09-10 15:04:31,669] Trial 30 finished with value: 0.2824168328918302 and parameters: {'C': 2.4351108700348965, 'l1_ratio': 0.4691344982215644}. Best is trial 5 with value: 0.23901927964648556.
[I 2026-09-10 15:04:35,034] Trial 32 finished with value: 0.25743565278188896 and parameters: {'C': 4.5217888508272255, 'l1_ratio': 0.017180766574030542}. Best is trial 5 with value: 0.23901927964648556.
[I 2026-09-10 15:04:43,751] Trial 34 finished with value: 0.23766564299799073 and parameters: {'C': 7.897507626576557, 'l1_ratio': 0.17067604771479017}. Best is trial 34 with value: 0.23766564299799073.
[I 2026-09-10 15:05:05,523] Trial 35 finished with value: 0.23916400794977194 and parameters: {'C': 7.389479603844414, 'l1_ratio': 0.1634450781375809}. Best is trial 34 with value: 0.23766564299799073.
[I 2026-09-10 15:05:06,986] Trial 38 finished with value: 0.23755572917603235 and parameters: {'C': 7.86988381545254, 'l1_ratio': 0.18172134904431037}. Best is trial 38 with value: 0.23755572917603235.
[I 2026-09-10 15:05:13,880] Trial 40 finished with value: 0.23468423546539574 and parameters: {'C': 9.31578911779135, 'l1_ratio': 0.17783467376196604}. Best is trial 40 with value: 0.23468423546539574.
[I 2026-09-10 15:05:17,294] Trial 33 finished with value: 0.24320493831689136 and parameters: {'C': 6.370972018849286, 'l1_ratio': 0.1445632471567589}. Best is trial 40 with value: 0.23468423546539574.
[I 2026-09-10 15:05:20,169] Trial 41 finished with value: 0.2457973049784581 and parameters: {'C': 5.718839386619592, 'l1_ratio': 0.17746776319342536}. Best is trial 40 with value: 0.23468423546539574.
[I 2026-09-10 15:05:20,231] Trial 37 finished with value: 0.23679157305319887 and parameters: {'C': 8.279054071501383, 'l1_ratio': 0.16615959554003407}. Best is trial 40 with value: 0.23468423546539574.
[I 2026-09-10 15:05:22,187] Trial 39 finished with value: 0.23781856738895962 and parameters: {'C': 7.951868596024422, 'l1_ratio': 0.15026233816879764}. Best is trial 40 with value: 0.23468423546539574.
[I 2026-09-10 15:05:23,941] Trial 42 finished with value: 0.2471254760733356 and parameters: {'C': 5.439115463408491, 'l1_ratio': 0.1909527903258881}. Best is trial 40 with value: 0.23468423546539574.
[I 2026-09-10 15:05:32,622] Trial 44 finished with value: 0.23418024634273543 and parameters: {'C': 9.281346358555725, 'l1_ratio': 0.22613036266766917}. Best is trial 44 with value: 0.23418024634273543.
[I 2026-09-10 15:05:33,993] Trial 36 finished with value: 0.24171839308048665 and parameters: {'C': 6.602281135210725, 'l1_ratio': 0.17595181939984447}. Best is trial 44 with value: 0.23418024634273543.
[I 2026-09-10 15:05:36,763] Trial 43 finished with value: 0.23815907125349045 and parameters: {'C': 7.5113027719319385, 'l1_ratio': 0.20663825741970926}. Best is trial 44 with value: 0.23418024634273543.
[I 2026-09-10 15:06:07,664] Trial 45 finished with value: 0.23384881646525427 and parameters: {'C': 9.623325512291972, 'l1_ratio': 0.21055173571099192}. Best is trial 45 with value: 0.23384881646525427.
[I 2026-09-10 15:06:26,598] Trial 46 finished with value: 0.2336894862748607 and parameters: {'C': 9.769860248439297, 'l1_ratio': 0.20847941995780492}. Best is trial 46 with value: 0.2336894862748607.
[I 2026-09-10 15:06:30,135] Trial 49 finished with value: 0.23499181838127967 and parameters: {'C': 8.996343627555513, 'l1_ratio': 0.19896944611641199}. Best is trial 46 with value: 0.2336894862748607.
[I 2026-09-10 15:06:33,210] Trial 48 finished with value: 0.23399129472051228 and parameters: {'C': 9.61352091835031, 'l1_ratio': 0.19811604087432066}. Best is trial 46 with value: 0.2336894862748607.
[I 2026-09-10 15:06:42,281] Trial 47 finished with value: 0.23356209563138636 and parameters: {'C': 9.952558188267066, 'l1_ratio': 0.19039735397173768}. Best is trial 47 with value: 0.23356209563138636.
[I 2026-09-10 15:06:51,529] Trial 51 finished with value: 0.2351006655476861 and parameters: {'C': 9.33091471573308, 'l1_ratio': 0.14130448009340202}. Best is trial 47 with value: 0.23356209563138636.
[I 2026-09-10 15:07:05,402] Trial 50 finished with value: 0.23429715006452012 and parameters: {'C': 9.584962931572772, 'l1_ratio': 0.17392939591458437}. Best is trial 47 with value: 0.23356209563138636.
[I 2026-09-10 15:07:07,322] Trial 52 finished with value: 0.2341752050382638 and parameters: {'C': 9.069296368236682, 'l1_ratio': 0.25666246230149925}. Best is trial 47 with value: 0.23356209563138636.
[I 2026-09-10 15:07:11,766] Trial 53 finished with value: 0.23702476440876877 and parameters: {'C': 7.759042203657124, 'l1_ratio': 0.24341606875113583}. Best is trial 47 with value: 0.23356209563138636.
[I 2026-09-10 15:07:15,333] Trial 58 finished with value: 0.23525622406647476 and parameters: {'C': 8.485733879717564, 'l1_ratio': 0.25805258403118403}. Best is trial 47 with value: 0.23356209563138636.
[I 2026-09-10 15:07:17,524] Trial 55 finished with value: 0.23302496740702824 and parameters: {'C': 9.740135564301188, 'l1_ratio': 0.26951424530113655}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:07:20,907] Trial 54 finished with value: 0.23409971196528664 and parameters: {'C': 9.144243679462454, 'l1_ratio': 0.25397133957344287}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:07:22,575] Trial 57 finished with value: 0.23318902767674632 and parameters: {'C': 9.825064552238903, 'l1_ratio': 0.24245499883031568}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:07:23,251] Trial 56 finished with value: 0.23314294873593422 and parameters: {'C': 9.777676951702048, 'l1_ratio': 0.2536411785417717}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:07:24,885] Trial 61 finished with value: 0.2862428288676318 and parameters: {'C': 2.4815076583862123, 'l1_ratio': 0.10454587028828814}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:07:33,810] Trial 60 finished with value: 0.23319187509980335 and parameters: {'C': 9.635091115055358, 'l1_ratio': 0.26571137879378787}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:07:35,780] Trial 59 finished with value: 0.23338090780293613 and parameters: {'C': 9.677786687977903, 'l1_ratio': 0.24532996882618552}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:07:43,603] Trial 63 finished with value: 0.2725443207029459 and parameters: {'C': 3.029023382359534, 'l1_ratio': 0.26483087518977677}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:07:54,080] Trial 64 finished with value: 0.2777865687743862 and parameters: {'C': 2.753339799150952, 'l1_ratio': 0.2814490810119095}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:08:02,548] Trial 65 finished with value: 0.28544865062408015 and parameters: {'C': 2.431771972083724, 'l1_ratio': 0.26976526586304717}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:08:18,394] Trial 68 finished with value: 0.28046596563384363 and parameters: {'C': 2.6372479213902014, 'l1_ratio': 0.26978043073553093}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:08:20,894] Trial 67 finished with value: 0.28307883437547876 and parameters: {'C': 2.5352738776324095, 'l1_ratio': 0.25182836124963687}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:08:22,134] Trial 70 finished with value: 0.2860837047910848 and parameters: {'C': 2.4028469606482408, 'l1_ratio': 0.2810932650396613}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:08:27,542] Trial 62 finished with value: 0.23313161401809174 and parameters: {'C': 9.7475450888654, 'l1_ratio': 0.26088134110865085}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:08:35,741] Trial 71 finished with value: 0.2828500505799144 and parameters: {'C': 2.5291021351940546, 'l1_ratio': 0.2841216437466316}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:08:39,098] Trial 69 finished with value: 0.2847432334556329 and parameters: {'C': 2.457941919513795, 'l1_ratio': 0.2733808746819972}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:08:40,169] Trial 74 finished with value: 0.28433511898837477 and parameters: {'C': 2.4235959674345575, 'l1_ratio': 0.37490473413404257}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:08:41,174] Trial 72 finished with value: 0.27987641255976603 and parameters: {'C': 2.598066127212674, 'l1_ratio': 0.3763105682218342}. Best is trial 55 with value: 0.23302496740702824.
[I 2026-09-10 15:08:41,276] Trial 66 finished with value: 0.23281955044453992 and parameters: {'C': 9.959878703826652, 'l1_ratio': 0.26354689644124907}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:08:44,761] Trial 73 finished with value: 0.2799392691068181 and parameters: {'C': 2.5975510488755154, 'l1_ratio': 0.3751581027762154}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:08:57,658] Trial 75 finished with value: 0.2832287809538118 and parameters: {'C': 2.465295014654508, 'l1_ratio': 0.37630377101959567}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:09:11,622] Trial 78 finished with value: 0.24997893671666954 and parameters: {'C': 4.593058540712719, 'l1_ratio': 0.3522689172954053}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:09:20,108] Trial 76 finished with value: 0.2474770996935438 and parameters: {'C': 4.825700483891544, 'l1_ratio': 0.38176888470006975}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:09:33,995] Trial 79 finished with value: 0.25266791850212433 and parameters: {'C': 4.3096381861973905, 'l1_ratio': 0.34876794657228916}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:09:35,688] Trial 77 finished with value: 0.2496957387582331 and parameters: {'C': 4.591187572746859, 'l1_ratio': 0.36523771013330686}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:09:45,350] Trial 81 finished with value: 0.2500667685355548 and parameters: {'C': 4.546825716264145, 'l1_ratio': 0.3671232078623083}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:09:48,557] Trial 83 finished with value: 0.24942163770025672 and parameters: {'C': 4.59443116343242, 'l1_ratio': 0.3773491912612009}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:02,706] Trial 82 finished with value: 0.24959035060839577 and parameters: {'C': 4.560438067383589, 'l1_ratio': 0.3816805066660657}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:05,692] Trial 89 finished with value: 0.2511353154299559 and parameters: {'C': 4.508500314269919, 'l1_ratio': 0.33412479661966177}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:12,364] Trial 84 finished with value: 0.25043143516456723 and parameters: {'C': 4.439338114867779, 'l1_ratio': 0.3921508572006802}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:14,260] Trial 80 finished with value: 0.2504329432060785 and parameters: {'C': 4.500276766679245, 'l1_ratio': 0.36834350098380503}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:16,237] Trial 85 finished with value: 0.2532080756236429 and parameters: {'C': 4.24059590946581, 'l1_ratio': 0.35579988859897405}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:18,890] Trial 87 finished with value: 0.25182230190473 and parameters: {'C': 4.447638912964598, 'l1_ratio': 0.32702193433211313}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:19,820] Trial 88 finished with value: 0.25066682807544854 and parameters: {'C': 4.584947697961786, 'l1_ratio': 0.3243688267421525}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:24,952] Trial 90 finished with value: 0.24977066150920382 and parameters: {'C': 4.648985969628445, 'l1_ratio': 0.3393130455041641}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:29,625] Trial 92 finished with value: 0.25915389590925697 and parameters: {'C': 3.7608256101389657, 'l1_ratio': 0.34091121755363063}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:38,360] Trial 86 finished with value: 0.24983785773958833 and parameters: {'C': 4.583408767388416, 'l1_ratio': 0.362141060050549}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:43,282] Trial 93 finished with value: 0.25899255586367587 and parameters: {'C': 3.807806393134664, 'l1_ratio': 0.32003309641582656}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:45,839] Trial 91 finished with value: 0.25152813647284916 and parameters: {'C': 4.474720586334426, 'l1_ratio': 0.3287246423509745}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:10:59,336] Trial 94 finished with value: 0.24325051227226907 and parameters: {'C': 5.766789993783511, 'l1_ratio': 0.30392320155220737}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:11:00,546] Trial 96 finished with value: 0.2469246891363685 and parameters: {'C': 5.732842956156396, 'l1_ratio': 0.11358690141432459}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:11:06,573] Trial 97 finished with value: 0.2418200325410999 and parameters: {'C': 5.9885945378173195, 'l1_ratio': 0.32755267344042854}. Best is trial 66 with value: 0.23281955044453992.
[I 2026-09-10 15:11:07,246] Trial 95 finished with value: 0.24081551451511016 and parameters: {'C': 5.881735184423302, 'l1_ratio': 0.41012600367150276}. Best is trial 66 with value: 0.23281955044453992.

In [14]:
scores = []
parameters = []

for split, selected_features in zip(splits, features):
    X_train, y_train, X_val, y_val = split["X_train_raw"], split["y_train"], split["X_val_raw"], split["y_val"]

    X_train = X_train[selected_features]
    X_val = X_val[selected_features]

    # objective = make_objective(X_train, y_train, X_val, y_val)
    objective = make_objective(X_train.values, y_train.values)
    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=500, n_jobs=-1)
    params = study.best_params
    parameters.append(params)
    print("Best parameters:", params)

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled   = scaler.transform(X_val)

    selector = VarianceThreshold(threshold=0.01)
    X_train_sel = selector.fit_transform(X_train_scaled)
    X_val_sel   = selector.transform(X_val_scaled)

    model = LogisticRegression(C=params['C'], l1_ratio=params['l1_ratio'], solver='saga', max_iter=5000)
    model.fit(X_train_sel, y_train)

    val_pred = model.predict(X_val_sel)
    scores.append(roc_auc_score(y_val, val_pred))

print(f"Scores: {scores}")
print(f"Parameters: {parameters}")
print(f"Mean roc-auc: {np.mean(scores)}")

[I 2026-09-10 16:47:06,955] A new study created in memory with name: no-name-cebe2477-c52a-46de-aa74-99109b2c299c

[I 2026-09-10 16:47:07,411] Trial 0 finished with value: 0.6481059203548638 and parameters: {'C': 0.8009075758291069, 'l1_ratio': 0.8749186930231899}. Best is trial 0 with value: 0.6481059203548638.
[I 2026-09-10 16:47:07,444] Trial 11 finished with value: 0.6536630878089194 and parameters: {'C': 0.004545390571282353, 'l1_ratio': 0.03806137100531859}. Best is trial 0 with value: 0.6481059203548638.
[I 2026-09-10 16:47:07,452] Trial 1 finished with value: 0.6931119311629498 and parameters: {'C': 0.0014290123579572434, 'l1_ratio': 0.5140990386538604}. Best is trial 0 with value: 0.6481059203548638.
[I 2026-09-10 16:47:07,470] Trial 3 finished with value: 0.6931095649517889 and parameters: {'C': 0.0019407897513168209, 'l1_ratio': 0.3686955611143955}. Best is trial 0 with value: 0.6481059203548638.
[I 2026-09-10 16:47:07,477] Trial 2 finished with value: 0.6649163167805335 and parameters: {'C': 0.008125344180859705, 'l1_ratio': 0.39074730739353836}. Best is trial 0 with value: 0.6481059203548638.
[I 2026-09-10 16:47:07,478] Trial 8 finished with value: 0.6760558076768441 and parameters: {'C': 0.0010440992238268496, 'l1_ratio': 0.04632704912573149}. Best is trial 0 with value: 0.6481059203548638.
[I 2026-09-10 16:47:07,493] Trial 12 finished with value: 0.6937153713457445 and parameters: {'C': 0.002958552466121934, 'l1_ratio': 0.807171554812417}. Best is trial 0 with value: 0.6481059203548638.
[I 2026-09-10 16:47:07,495] Trial 10 finished with value: 0.6935764148148604 and parameters: {'C': 0.0012083356507073793, 'l1_ratio': 0.7490322488429338}. Best is trial 0 with value: 0.6481059203548638.
[I 2026-09-10 16:47:07,512] Trial 15 finished with value: 0.6476436455509276 and parameters: {'C': 0.13771259960323246, 'l1_ratio': 0.17744248817742192}. Best is trial 15 with value: 0.6476436455509276.
[I 2026-09-10 16:47:07,518] Trial 6 finished with value: 0.6483001724176627 and parameters: {'C': 0.9851969046504996, 'l1_ratio': 0.12295495772251364}. Best is trial 15 with value: 0.6476436455509276.
[I 2026-09-10 16:47:07,528] Trial 7 finished with value: 0.6482924101635972 and parameters: {'C': 0.9061760171356529, 'l1_ratio': 0.09142932723847652}. Best is trial 15 with value: 0.6476436455509276.
[I 2026-09-10 16:47:07,529] Trial 9 finished with value: 0.6481144227926465 and parameters: {'C': 0.44161763709929264, 'l1_ratio': 0.04184732412427894}. Best is trial 15 with value: 0.6476436455509276.
[I 2026-09-10 16:47:07,549] Trial 4 finished with value: 0.6485026563056211 and parameters: {'C': 7.010697047682148, 'l1_ratio': 0.22260044063843765}. Best is trial 15 with value: 0.6476436455509276.
[I 2026-09-10 16:47:07,590] Trial 5 finished with value: 0.648229265295498 and parameters: {'C': 0.8452027043752723, 'l1_ratio': 0.24800682349460934}. Best is trial 15 with value: 0.6476436455509276.
[I 2026-09-10 16:47:07,610] Trial 13 finished with value: 0.6473335280350379 and parameters: {'C': 0.033020177476572335, 'l1_ratio': 0.10919437901214657}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:07,618] Trial 14 finished with value: 0.6483359279800169 and parameters: {'C': 1.9713760204960227, 'l1_ratio': 0.6385905612042062}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:07,956] Trial 17 finished with value: 0.6484892544383594 and parameters: {'C': 9.401846937235321, 'l1_ratio': 0.824632041503402}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,001] Trial 20 finished with value: 0.6795644012496408 and parameters: {'C': 0.006920039838286845, 'l1_ratio': 0.5852420522801457}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,010] Trial 16 finished with value: 0.6480551435772014 and parameters: {'C': 0.09230406689193386, 'l1_ratio': 0.6359215270120208}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,015] Trial 18 finished with value: 0.6484723952317152 and parameters: {'C': 7.312260321949366, 'l1_ratio': 0.8494943187705305}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,016] Trial 19 finished with value: 0.6480803761882947 and parameters: {'C': 0.7028985196851437, 'l1_ratio': 0.9471476683881564}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,050] Trial 22 finished with value: 0.6493747040852138 and parameters: {'C': 0.0825740797295029, 'l1_ratio': 0.9801162826903993}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,058] Trial 24 finished with value: 0.6498130497746419 and parameters: {'C': 0.06759345609067129, 'l1_ratio': 0.9317442080461252}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,067] Trial 25 finished with value: 0.6494680103722468 and parameters: {'C': 0.07657225997767027, 'l1_ratio': 0.9347415353742331}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,072] Trial 23 finished with value: 0.6489313872681928 and parameters: {'C': 0.0958660361355227, 'l1_ratio': 0.9418214436545902}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,108] Trial 26 finished with value: 0.6492910141048369 and parameters: {'C': 0.082984032968838, 'l1_ratio': 0.9560557215030875}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,114] Trial 28 finished with value: 0.6474286286754174 and parameters: {'C': 0.057188220443710136, 'l1_ratio': 0.242335708033299}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,118] Trial 27 finished with value: 0.6474286589172356 and parameters: {'C': 0.05533065030006379, 'l1_ratio': 0.23809283670706385}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,130] Trial 21 finished with value: 0.6478914271451797 and parameters: {'C': 0.09388029628816126, 'l1_ratio': 0.5927297138905676}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,159] Trial 31 finished with value: 0.6475791640623859 and parameters: {'C': 0.048629904481214584, 'l1_ratio': 0.2565415841269425}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,166] Trial 30 finished with value: 0.6474741830386532 and parameters: {'C': 0.05447526257095284, 'l1_ratio': 0.25785106329114604}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,174] Trial 29 finished with value: 0.6474533445097002 and parameters: {'C': 0.04916324879669073, 'l1_ratio': 0.22819539473239353}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,474] Trial 32 finished with value: 0.6475006962786255 and parameters: {'C': 0.042167098732525055, 'l1_ratio': 0.2065335282293701}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,519] Trial 36 finished with value: 0.647396905850406 and parameters: {'C': 0.043507391344583604, 'l1_ratio': 0.18332903945126156}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,525] Trial 33 finished with value: 0.6480021233592916 and parameters: {'C': 0.03571421788451668, 'l1_ratio': 0.228431108047142}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,548] Trial 35 finished with value: 0.6474630618851865 and parameters: {'C': 0.04387264636773096, 'l1_ratio': 0.20665779872005532}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,571] Trial 34 finished with value: 0.6474205621324385 and parameters: {'C': 0.062223781802417166, 'l1_ratio': 0.23093724631855678}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,605] Trial 37 finished with value: 0.6476931413287297 and parameters: {'C': 0.03706816294844006, 'l1_ratio': 0.20762525588280042}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,631] Trial 44 finished with value: 0.6506007921645716 and parameters: {'C': 0.023053902172847265, 'l1_ratio': 0.34512485480583066}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,637] Trial 39 finished with value: 0.6487769741858334 and parameters: {'C': 0.023914952235695373, 'l1_ratio': 0.1841628987556555}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,649] Trial 43 finished with value: 0.6511743001974637 and parameters: {'C': 0.021026206395960367, 'l1_ratio': 0.3506781761559964}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,652] Trial 42 finished with value: 0.6513322776798949 and parameters: {'C': 0.01868187154296949, 'l1_ratio': 0.31134122173806905}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,652] Trial 40 finished with value: 0.6501208541123451 and parameters: {'C': 0.023144491950889905, 'l1_ratio': 0.3018317825127078}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,655] Trial 38 finished with value: 0.6493694901132756 and parameters: {'C': 0.021764463411149945, 'l1_ratio': 0.20323369673268626}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,667] Trial 46 finished with value: 0.6535383808866669 and parameters: {'C': 0.016078672021192442, 'l1_ratio': 0.3613104501062194}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,678] Trial 45 finished with value: 0.650771569430961 and parameters: {'C': 0.022591070167870573, 'l1_ratio': 0.351075643379172}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,683] Trial 41 finished with value: 0.6498680233541055 and parameters: {'C': 0.024302940753151855, 'l1_ratio': 0.2919386952772951}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,700] Trial 47 finished with value: 0.652039281487881 and parameters: {'C': 0.01799269496414268, 'l1_ratio': 0.33817631124913605}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:08,993] Trial 48 finished with value: 0.6501601178059254 and parameters: {'C': 0.026053552454272624, 'l1_ratio': 0.3553555831165847}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,055] Trial 49 finished with value: 0.6523356693812257 and parameters: {'C': 0.018437525648848457, 'l1_ratio': 0.36525727408255426}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,064] Trial 51 finished with value: 0.6534194214794107 and parameters: {'C': 0.015845772807005932, 'l1_ratio': 0.3498767692189721}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,080] Trial 52 finished with value: 0.65238884225627 and parameters: {'C': 0.01933555841090589, 'l1_ratio': 0.38975012937848486}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,098] Trial 50 finished with value: 0.6509514350079266 and parameters: {'C': 0.021893554126496424, 'l1_ratio': 0.3517697851355329}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,151] Trial 54 finished with value: 0.6478518790224631 and parameters: {'C': 0.25454577817307006, 'l1_ratio': 0.32053878846457995}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,155] Trial 55 finished with value: 0.6476410407632767 and parameters: {'C': 0.1500357530605282, 'l1_ratio': 0.4702655692856795}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,165] Trial 56 finished with value: 0.6478400697602579 and parameters: {'C': 0.2400049348145863, 'l1_ratio': 0.434677649199193}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,186] Trial 53 finished with value: 0.6536123913992924 and parameters: {'C': 0.015586624937271872, 'l1_ratio': 0.350814694486518}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,222] Trial 57 finished with value: 0.6477951274942717 and parameters: {'C': 0.19054515073953768, 'l1_ratio': 0.43382721477687003}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,223] Trial 58 finished with value: 0.6478179524440424 and parameters: {'C': 0.20460629061576568, 'l1_ratio': 0.45523813593205553}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,273] Trial 59 finished with value: 0.6477956444905525 and parameters: {'C': 0.19141475607180403, 'l1_ratio': 0.43932181464125913}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,274] Trial 60 finished with value: 0.6477003585264939 and parameters: {'C': 0.15527937283373425, 'l1_ratio': 0.4281654267867392}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,277] Trial 62 finished with value: 0.6477086178111715 and parameters: {'C': 0.1578518755275506, 'l1_ratio': 0.4322552679133618}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,289] Trial 61 finished with value: 0.6478010451784486 and parameters: {'C': 0.193018039363104, 'l1_ratio': 0.43483357871521294}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,300] Trial 63 finished with value: 0.6477994314483716 and parameters: {'C': 0.21747015225797164, 'l1_ratio': 0.13541608227591914}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,539] Trial 64 finished with value: 0.6478092842481338 and parameters: {'C': 0.20267585718788242, 'l1_ratio': 0.43879597752214533}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,598] Trial 66 finished with value: 0.6477006356736226 and parameters: {'C': 0.16907053857470716, 'l1_ratio': 0.11733299980035038}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,615] Trial 67 finished with value: 0.6477313710647792 and parameters: {'C': 0.18292234196424081, 'l1_ratio': 0.14313290072358728}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,621] Trial 65 finished with value: 0.6478347453675234 and parameters: {'C': 0.23527950929573474, 'l1_ratio': 0.4210751725748798}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,703] Trial 70 finished with value: 0.6517524626794373 and parameters: {'C': 0.009986500107276926, 'l1_ratio': 0.1309321765709317}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,713] Trial 71 finished with value: 0.6532196004002516 and parameters: {'C': 0.008158266064861643, 'l1_ratio': 0.1268267246846021}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,722] Trial 69 finished with value: 0.6515591318309071 and parameters: {'C': 0.010031113629073836, 'l1_ratio': 0.12532514130304878}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,726] Trial 68 finished with value: 0.6478179165277063 and parameters: {'C': 0.22577106163321953, 'l1_ratio': 0.1268330250775135}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,759] Trial 72 finished with value: 0.6519728941601279 and parameters: {'C': 0.009625463411714958, 'l1_ratio': 0.12961489089291084}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,786] Trial 75 finished with value: 0.6545715354052112 and parameters: {'C': 0.0073166788931134106, 'l1_ratio': 0.13393987880287306}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,788] Trial 74 finished with value: 0.6480010787896926 and parameters: {'C': 0.36058177353974674, 'l1_ratio': 0.13077040688919153}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,792] Trial 73 finished with value: 0.6509409388008637 and parameters: {'C': 0.01057414273037445, 'l1_ratio': 0.11296322581297419}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,801] Trial 76 finished with value: 0.6508105060921192 and parameters: {'C': 0.010895516783938807, 'l1_ratio': 0.11410958276580604}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,835] Trial 78 finished with value: 0.6473569033360961 and parameters: {'C': 0.056792910669700845, 'l1_ratio': 0.13070869634017818}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,837] Trial 77 finished with value: 0.6484337120606487 and parameters: {'C': 0.009478068114225257, 'l1_ratio': 0.002899119180463705}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:09,847] Trial 79 finished with value: 0.651055731161657 and parameters: {'C': 0.008543453591396072, 'l1_ratio': 0.07339998852993723}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:10,027] Trial 80 finished with value: 0.6481041759211529 and parameters: {'C': 0.010940379650700613, 'l1_ratio': 0.004361068768001006}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:10,166] Trial 83 finished with value: 0.6508083613360874 and parameters: {'C': 0.009397796796346614, 'l1_ratio': 0.08287041947582308}. Best is trial 13 with value: 0.6473335280350379.
[I 2026-09-10 16:47:10,168] Trial 81 finished with value: 0.6473182106644387 and parameters: {'C': 0.06184835342545779, 'l1_ratio': 0.09112002990750234}. Best is trial 81 with value: 0.6473182106644387.
[I 2026-09-10 16:47:10,224] Trial 82 finished with value: 0.6474181188164354 and parameters: {'C': 0.06647356478911902, 'l1_ratio': 0.1588625217825744}. Best is trial 81 with value: 0.6473182106644387.
[I 2026-09-10 16:47:10,251] Trial 84 finished with value: 0.6472143029054365 and parameters: {'C': 0.060508752205133604, 'l1_ratio': 0.012359584164050905}. Best is trial 84 with value: 0.6472143029054365.
[I 2026-09-10 16:47:10,265] Trial 86 finished with value: 0.6474548202478875 and parameters: {'C': 0.06130603129787866, 'l1_ratio': 0.2696200683065742}. Best is trial 84 with value: 0.6472143029054365.
[I 2026-09-10 16:47:10,278] Trial 88 finished with value: 0.6475248389115491 and parameters: {'C': 0.0534448838766206, 'l1_ratio': 0.26894848259118037}. Best is trial 84 with value: 0.6472143029054365.
[I 2026-09-10 16:47:10,312] Trial 87 finished with value: 0.6474664603244903 and parameters: {'C': 0.05730071963510745, 'l1_ratio': 0.26466420964924653}. Best is trial 84 with value: 0.6472143029054365.
[I 2026-09-10 16:47:10,332] Trial 91 finished with value: 0.6476342031180906 and parameters: {'C': 0.048233359497888734, 'l1_ratio': 0.2649280803578291}. Best is trial 84 with value: 0.6472143029054365.
[I 2026-09-10 16:47:10,351] Trial 85 finished with value: 0.6472773034806117 and parameters: {'C': 0.06083236444246227, 'l1_ratio': 0.07153526285350165}. Best is trial 84 with value: 0.6472143029054365.
[I 2026-09-10 16:47:10,367] Trial 92 finished with value: 0.6475778182261618 and parameters: {'C': 0.1125492162451615, 'l1_ratio': 0.17147511344047087}. Best is trial 84 with value: 0.6472143029054365.
[I 2026-09-10 16:47:10,381] Trial 89 finished with value: 0.6471666663848747 and parameters: {'C': 0.05456338489848681, 'l1_ratio': 7.612230028297695e-05}. Best is trial 89 with value: 0.6471666663848747.
[I 2026-09-10 16:47:10,401] Trial 90 finished with value: 0.6476110323670148 and parameters: {'C': 0.049429220007563474, 'l1_ratio': 0.2672237516136046}. Best is trial 89 with value: 0.6471666663848747.
[I 2026-09-10 16:47:10,429] Trial 95 finished with value: 0.647462151512126 and parameters: {'C': 0.061445383932487586, 'l1_ratio': 0.2749517652833223}. Best is trial 89 with value: 0.6471666663848747.
[I 2026-09-10 16:47:10,432] Trial 93 finished with value: 0.6474670880895366 and parameters: {'C': 0.05922277924647975, 'l1_ratio': 0.2741518919071335}. Best is trial 89 with value: 0.6471666663848747.
[I 2026-09-10 16:47:10,449] Trial 94 finished with value: 0.6474635478424687 and parameters: {'C': 0.060285097841283004, 'l1_ratio': 0.2723373519246439}. Best is trial 89 with value: 0.6471666663848747.
[I 2026-09-10 16:47:10,568] Trial 96 finished with value: 0.6474904707125715 and parameters: {'C': 0.05957160291706495, 'l1_ratio': 0.2832035661819316}. Best is trial 89 with value: 0.6471666663848747.
[I 2026-09-10 16:47:10,754] Trial 98 finished with value: 0.6474218175168523 and parameters: {'C': 0.05797382971783914, 'l1_ratio': 0.23783050430604102}. Best is trial 89 with value: 0.6471666663848747.

Best parameters: {'C': 0.03235284138708342, 'l1_ratio': 0.00011053604464882766}

[I 2026-09-10 16:47:25,346] Trial 1 finished with value: 0.6928373390755503 and parameters: {'C': 0.0013841341998630534, 'l1_ratio': 0.5678564816892332}. Best is trial 1 with value: 0.6928373390755503.
[I 2026-09-10 16:47:25,372] Trial 5 finished with value: 0.6541492613520374 and parameters: {'C': 5.8342738531589715, 'l1_ratio': 0.8820604762235407}. Best is trial 5 with value: 0.6541492613520374.
[I 2026-09-10 16:47:25,395] Trial 0 finished with value: 0.6540996443426714 and parameters: {'C': 2.3617966962682235, 'l1_ratio': 0.44186075742635456}. Best is trial 0 with value: 0.6540996443426714.
[I 2026-09-10 16:47:25,407] Trial 2 finished with value: 0.6892397595786484 and parameters: {'C': 0.002301508647150573, 'l1_ratio': 0.3217035845670806}. Best is trial 0 with value: 0.6540996443426714.
[I 2026-09-10 16:47:25,410] Trial 3 finished with value: 0.6530169309296598 and parameters: {'C': 0.05817648943415772, 'l1_ratio': 0.633993840946057}. Best is trial 3 with value: 0.6530169309296598.
[I 2026-09-10 16:47:25,415] Trial 4 finished with value: 0.6532893144015606 and parameters: {'C': 0.23768633268491185, 'l1_ratio': 0.4283328870751697}. Best is trial 3 with value: 0.6530169309296598.
[I 2026-09-10 16:47:25,435] Trial 14 finished with value: 0.6619809184976578 and parameters: {'C': 0.005572142683984367, 'l1_ratio': 0.2906737689971254}. Best is trial 3 with value: 0.6530169309296598.
[I 2026-09-10 16:47:25,442] Trial 7 finished with value: 0.6523259675218807 and parameters: {'C': 0.1360854012664942, 'l1_ratio': 0.9829490570318737}. Best is trial 7 with value: 0.6523259675218807.
[I 2026-09-10 16:47:25,459] Trial 6 finished with value: 0.6541666106197727 and parameters: {'C': 6.821881753107827, 'l1_ratio': 0.7086225844847721}. Best is trial 7 with value: 0.6523259675218807.
[I 2026-09-10 16:47:25,467] Trial 13 finished with value: 0.6528983576077969 and parameters: {'C': 0.22678239043191023, 'l1_ratio': 0.6967145614166036}. Best is trial 7 with value: 0.6523259675218807.
[I 2026-09-10 16:47:25,480] Trial 8 finished with value: 0.6540945176310771 and parameters: {'C': 1.7317319430826927, 'l1_ratio': 0.21488444453095212}. Best is trial 7 with value: 0.6523259675218807.
[I 2026-09-10 16:47:25,480] Trial 11 finished with value: 0.6522764715461428 and parameters: {'C': 0.08574156295000031, 'l1_ratio': 0.643515356852398}. Best is trial 11 with value: 0.6522764715461428.
[I 2026-09-10 16:47:25,480] Trial 9 finished with value: 0.6532148174424077 and parameters: {'C': 0.32262504712653606, 'l1_ratio': 0.7980724022413498}. Best is trial 11 with value: 0.6522764715461428.
[I 2026-09-10 16:47:25,481] Trial 10 finished with value: 0.6541512057813582 and parameters: {'C': 6.289110697325575, 'l1_ratio': 0.971171630048422}. Best is trial 11 with value: 0.6522764715461428.
[I 2026-09-10 16:47:25,526] Trial 15 finished with value: 0.6534839599276634 and parameters: {'C': 0.3538171040032745, 'l1_ratio': 0.595018671932013}. Best is trial 11 with value: 0.6522764715461428.
[I 2026-09-10 16:47:25,529] Trial 12 finished with value: 0.6533437460605288 and parameters: {'C': 0.2246164260451446, 'l1_ratio': 0.3460714358426983}. Best is trial 11 with value: 0.6522764715461428.
[I 2026-09-10 16:47:25,894] Trial 16 finished with value: 0.6541623086236102 and parameters: {'C': 4.327844264093265, 'l1_ratio': 0.320929301868223}. Best is trial 11 with value: 0.6522764715461428.
[I 2026-09-10 16:47:25,915] Trial 17 finished with value: 0.6588265155673002 and parameters: {'C': 0.004781154502417145, 'l1_ratio': 0.14558232145661698}. Best is trial 11 with value: 0.6522764715461428.
[I 2026-09-10 16:47:25,952] Trial 18 finished with value: 0.6524924724220984 and parameters: {'C': 0.19246541478144052, 'l1_ratio': 0.8742406470571823}. Best is trial 11 with value: 0.6522764715461428.
[I 2026-09-10 16:47:25,953] Trial 20 finished with value: 0.6541941614041897 and parameters: {'C': 6.2201678249910515, 'l1_ratio': 0.03970287842888853}. Best is trial 11 with value: 0.6522764715461428.
[I 2026-09-10 16:47:25,960] Trial 19 finished with value: 0.6515238880048955 and parameters: {'C': 0.01631053355508149, 'l1_ratio': 0.0001079020977776679}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:25,961] Trial 21 finished with value: 0.651598163589763 and parameters: {'C': 0.01983271511513931, 'l1_ratio': 0.01263928436888262}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:25,977] Trial 23 finished with value: 0.6516947931042418 and parameters: {'C': 0.024877569352370354, 'l1_ratio': 0.03539227637815534}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,010] Trial 22 finished with value: 0.6518129962887311 and parameters: {'C': 0.01886753430789162, 'l1_ratio': 0.07960594436972768}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,034] Trial 24 finished with value: 0.6517170815839418 and parameters: {'C': 0.02524233319868216, 'l1_ratio': 0.011709576309800518}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,049] Trial 26 finished with value: 0.6517872370935505 and parameters: {'C': 0.02351440547479552, 'l1_ratio': 0.10010342498890945}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,072] Trial 27 finished with value: 0.6522614599482142 and parameters: {'C': 0.0180300981585248, 'l1_ratio': 0.1227410077743798}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,080] Trial 29 finished with value: 0.6517663990572906 and parameters: {'C': 0.029229016318488083, 'l1_ratio': 0.078799408186215}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,094] Trial 25 finished with value: 0.6516878690477894 and parameters: {'C': 0.02449017595424155, 'l1_ratio': 0.04993132936871769}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,098] Trial 28 finished with value: 0.6572430182888658 and parameters: {'C': 0.02060875435990776, 'l1_ratio': 0.9367453965834702}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,101] Trial 30 finished with value: 0.6518528867248626 and parameters: {'C': 0.030698640607816585, 'l1_ratio': 0.029462490326130353}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,158] Trial 31 finished with value: 0.6515883700975135 and parameters: {'C': 0.018802599385322163, 'l1_ratio': 0.014535397510272996}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,467] Trial 32 finished with value: 0.655575100948764 and parameters: {'C': 0.02930356424072661, 'l1_ratio': 0.9921426368520884}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,469] Trial 33 finished with value: 0.6551915380475096 and parameters: {'C': 0.03258780149206022, 'l1_ratio': 0.984247299454576}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,504] Trial 34 finished with value: 0.6516862015200023 and parameters: {'C': 0.02401004690571249, 'l1_ratio': 0.011954305852556746}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,537] Trial 37 finished with value: 0.6517188450849281 and parameters: {'C': 0.025311766207657724, 'l1_ratio': 0.006340059820189901}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,545] Trial 35 finished with value: 0.6516378587806246 and parameters: {'C': 0.021463946258471735, 'l1_ratio': 0.025111631790890716}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,548] Trial 36 finished with value: 0.6517847800966455 and parameters: {'C': 0.027459278222950655, 'l1_ratio': 0.0038188381477568104}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,612] Trial 39 finished with value: 0.6523747371602828 and parameters: {'C': 0.016188312834417167, 'l1_ratio': 0.11313024717148293}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,616] Trial 38 finished with value: 0.6517274935024003 and parameters: {'C': 0.025507017451598675, 'l1_ratio': 0.002366525488843342}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,621] Trial 43 finished with value: 0.6561807260111472 and parameters: {'C': 0.00809675376833865, 'l1_ratio': 0.17728375588659268}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,637] Trial 40 finished with value: 0.6570080955073028 and parameters: {'C': 0.007204537477279249, 'l1_ratio': 0.18476845074578163}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,645] Trial 45 finished with value: 0.6559928076680088 and parameters: {'C': 0.008776524756267293, 'l1_ratio': 0.19046213628479328}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,649] Trial 42 finished with value: 0.656650646425996 and parameters: {'C': 0.008171871701171339, 'l1_ratio': 0.20553472655162133}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,654] Trial 44 finished with value: 0.6563549367921633 and parameters: {'C': 0.008390522941080027, 'l1_ratio': 0.19700259519893207}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,684] Trial 46 finished with value: 0.6588364518130041 and parameters: {'C': 0.005745697322913116, 'l1_ratio': 0.19993040854324012}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,684] Trial 41 finished with value: 0.6568740560087936 and parameters: {'C': 0.008346334949676905, 'l1_ratio': 0.22608367718992117}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,772] Trial 47 finished with value: 0.6560052253868178 and parameters: {'C': 0.008596907541008777, 'l1_ratio': 0.1848543031973614}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:26,976] Trial 48 finished with value: 0.6560167743470366 and parameters: {'C': 0.00839678965347658, 'l1_ratio': 0.17870375730247068}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,009] Trial 49 finished with value: 0.6568129674645452 and parameters: {'C': 0.007858394305048966, 'l1_ratio': 0.20207129305692334}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,027] Trial 50 finished with value: 0.6560391527732058 and parameters: {'C': 0.008621093685027552, 'l1_ratio': 0.187685179626993}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,070] Trial 52 finished with value: 0.6573224634179115 and parameters: {'C': 0.007485169390565956, 'l1_ratio': 0.2168157562482921}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,071] Trial 53 finished with value: 0.655663778914641 and parameters: {'C': 0.009212366276424992, 'l1_ratio': 0.18383924707773558}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,091] Trial 51 finished with value: 0.6553305180803954 and parameters: {'C': 0.010008214135550893, 'l1_ratio': 0.1841920133661529}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,127] Trial 57 finished with value: 0.683614978646107 and parameters: {'C': 0.0020691122609343047, 'l1_ratio': 0.2400272912397068}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,219] Trial 54 finished with value: 0.656363527882071 and parameters: {'C': 0.008498742151067825, 'l1_ratio': 0.20144452859116924}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,220] Trial 58 finished with value: 0.6524580214848439 and parameters: {'C': 0.06260561658197164, 'l1_ratio': 0.0730262220412128}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,222] Trial 59 finished with value: 0.6652951888900153 and parameters: {'C': 0.0025557323210723053, 'l1_ratio': 0.12741503179218236}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,252] Trial 56 finished with value: 0.6519890197928613 and parameters: {'C': 0.058579128750804885, 'l1_ratio': 0.265826998409782}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,265] Trial 55 finished with value: 0.6523796863728325 and parameters: {'C': 0.05858889822244855, 'l1_ratio': 0.07731375738508674}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,304] Trial 60 finished with value: 0.6520226606292889 and parameters: {'C': 0.06127210929104597, 'l1_ratio': 0.26040087478802476}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,313] Trial 61 finished with value: 0.6524229555455158 and parameters: {'C': 0.060780254559521726, 'l1_ratio': 0.0742622096309784}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,331] Trial 62 finished with value: 0.6523587812563301 and parameters: {'C': 0.05648272326805435, 'l1_ratio': 0.07011637115564347}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,375] Trial 63 finished with value: 0.6519472113374261 and parameters: {'C': 0.05289783899624872, 'l1_ratio': 0.2527046324703579}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,560] Trial 64 finished with value: 0.6810721013946563 and parameters: {'C': 0.0023833802914571657, 'l1_ratio': 0.25938586157585614}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,644] Trial 66 finished with value: 0.6523107472340375 and parameters: {'C': 0.05184038453740407, 'l1_ratio': 0.05424536613174491}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,681] Trial 65 finished with value: 0.6526440886341623 and parameters: {'C': 0.07428058066973603, 'l1_ratio': 0.0729720624608699}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,724] Trial 67 finished with value: 0.6521739866875933 and parameters: {'C': 0.047210946927631135, 'l1_ratio': 0.06857432023899385}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,725] Trial 68 finished with value: 0.6523407297140266 and parameters: {'C': 0.05467965148804653, 'l1_ratio': 0.06395342564343945}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,744] Trial 70 finished with value: 0.6523563063613189 and parameters: {'C': 0.05467391390464302, 'l1_ratio': 0.056851370158451035}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,797] Trial 69 finished with value: 0.6523111785732103 and parameters: {'C': 0.053108822027968176, 'l1_ratio': 0.06410566295323257}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,836] Trial 74 finished with value: 0.6519088077375971 and parameters: {'C': 0.013839944219269503, 'l1_ratio': 0.05151257824761184}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,847] Trial 73 finished with value: 0.6521075290451536 and parameters: {'C': 0.04385696562654286, 'l1_ratio': 0.06499491202513258}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,873] Trial 76 finished with value: 0.6518394753379984 and parameters: {'C': 0.01436224695694712, 'l1_ratio': 0.04839824748872443}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,874] Trial 71 finished with value: 0.6522654973527111 and parameters: {'C': 0.04991961242662181, 'l1_ratio': 0.05672444492990153}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,877] Trial 72 finished with value: 0.6530721604665478 and parameters: {'C': 0.11370873215210824, 'l1_ratio': 0.04645305346715556}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,879] Trial 77 finished with value: 0.6530010646464783 and parameters: {'C': 0.10449695796409043, 'l1_ratio': 0.04722124230576807}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,911] Trial 75 finished with value: 0.653069777297501 and parameters: {'C': 0.11400516080128874, 'l1_ratio': 0.05147410229044236}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,923] Trial 79 finished with value: 0.6518296768667325 and parameters: {'C': 0.013481211389243191, 'l1_ratio': 0.039940530567013584}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:27,945] Trial 78 finished with value: 0.6517582283437202 and parameters: {'C': 0.015392583287569709, 'l1_ratio': 0.04542586901386499}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,176] Trial 80 finished with value: 0.651828558743937 and parameters: {'C': 0.013585556974441353, 'l1_ratio': 0.04066212512630199}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,249] Trial 82 finished with value: 0.6518423299577494 and parameters: {'C': 0.013884372945680882, 'l1_ratio': 0.0447472966879702}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,263] Trial 81 finished with value: 0.6531477557100511 and parameters: {'C': 0.014863909866974124, 'l1_ratio': 0.14156359417829037}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,267] Trial 84 finished with value: 0.6536424113392154 and parameters: {'C': 0.013540203838536139, 'l1_ratio': 0.1480397890314657}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,306] Trial 86 finished with value: 0.651734971419598 and parameters: {'C': 0.013141716091204517, 'l1_ratio': 0.026957128482335502}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,309] Trial 83 finished with value: 0.6517388152412787 and parameters: {'C': 0.01309947902589693, 'l1_ratio': 0.027196676031007273}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,350] Trial 85 finished with value: 0.6516744264697942 and parameters: {'C': 0.01431855293644323, 'l1_ratio': 0.025984119589490193}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,387] Trial 87 finished with value: 0.6539070955546277 and parameters: {'C': 0.012631521297521951, 'l1_ratio': 0.14663293884545253}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,446] Trial 89 finished with value: 0.6539538176958462 and parameters: {'C': 0.012026341072882148, 'l1_ratio': 0.1390455692715184}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,461] Trial 90 finished with value: 0.6516141868467272 and parameters: {'C': 0.013997527421921768, 'l1_ratio': 0.01463347053683419}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,473] Trial 91 finished with value: 0.6524097044232194 and parameters: {'C': 0.01978715724186909, 'l1_ratio': 0.15136557169773823}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,490] Trial 92 finished with value: 0.6518672076446327 and parameters: {'C': 0.038540519212413846, 'l1_ratio': 0.1423995758689242}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,493] Trial 88 finished with value: 0.6531660350699482 and parameters: {'C': 0.12296267103600753, 'l1_ratio': 0.019557141218535634}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,496] Trial 94 finished with value: 0.6518412620553357 and parameters: {'C': 0.03615862322700176, 'l1_ratio': 0.1368458491209773}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,510] Trial 95 finished with value: 0.652027114791728 and parameters: {'C': 0.036728222534707915, 'l1_ratio': 0.01515821648676192}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,522] Trial 93 finished with value: 0.6518570490310197 and parameters: {'C': 0.038040172043405485, 'l1_ratio': 0.1464902940299563}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,746] Trial 96 finished with value: 0.6516054447451525 and parameters: {'C': 0.020709762939945885, 'l1_ratio': 0.0044756891748672}. Best is trial 19 with value: 0.6515238880048955.
[I 2026-09-10 16:47:28,783] Trial 97 finished with value: 0.6520406773256247 and parameters: {'C': 0.03704035726810508, 'l1_ratio': 0.006065034203424108}. Best is trial 19 with value: 0.6515238880048955.

Best parameters: {'C': 0.016125302529960882, 'l1_ratio': 0.0002552884450807108}

[I 2026-09-10 16:47:43,553] Trial 7 finished with value: 0.6927873769305143 and parameters: {'C': 0.00243182622800162, 'l1_ratio': 0.4589615410726191}. Best is trial 7 with value: 0.6927873769305143.
[I 2026-09-10 16:47:43,582] Trial 4 finished with value: 0.6634197981392269 and parameters: {'C': 0.4193643353912109, 'l1_ratio': 0.8886645085041521}. Best is trial 4 with value: 0.6634197981392269.
[I 2026-09-10 16:47:43,615] Trial 6 finished with value: 0.6650975197461421 and parameters: {'C': 0.053147839949292154, 'l1_ratio': 0.4559803686850875}. Best is trial 4 with value: 0.6634197981392269.
[I 2026-09-10 16:47:43,619] Trial 0 finished with value: 0.6659650789288424 and parameters: {'C': 0.00882391776461598, 'l1_ratio': 0.1494898926228342}. Best is trial 4 with value: 0.6634197981392269.
[I 2026-09-10 16:47:43,624] Trial 5 finished with value: 0.6645252416988158 and parameters: {'C': 0.7591317609353488, 'l1_ratio': 0.15644504664857162}. Best is trial 4 with value: 0.6634197981392269.
[I 2026-09-10 16:47:43,625] Trial 2 finished with value: 0.663767229805256 and parameters: {'C': 0.39791987442045806, 'l1_ratio': 0.47295119882542513}. Best is trial 4 with value: 0.6634197981392269.
[I 2026-09-10 16:47:43,626] Trial 1 finished with value: 0.6633809953168787 and parameters: {'C': 0.33381726346604734, 'l1_ratio': 0.7474621509943897}. Best is trial 1 with value: 0.6633809953168787.
[I 2026-09-10 16:47:43,628] Trial 10 finished with value: 0.692779616302184 and parameters: {'C': 0.0013084883497010724, 'l1_ratio': 0.20693716245971983}. Best is trial 1 with value: 0.6633809953168787.
[I 2026-09-10 16:47:43,636] Trial 11 finished with value: 0.664906509598742 and parameters: {'C': 7.33180554489792, 'l1_ratio': 0.10026394307637865}. Best is trial 1 with value: 0.6633809953168787.
[I 2026-09-10 16:47:43,637] Trial 3 finished with value: 0.6640307484524214 and parameters: {'C': 0.7876784260729125, 'l1_ratio': 0.7124407541352581}. Best is trial 1 with value: 0.6633809953168787.
[I 2026-09-10 16:47:43,654] Trial 13 finished with value: 0.6634545677246779 and parameters: {'C': 0.23957875137517282, 'l1_ratio': 0.46277034620265944}. Best is trial 1 with value: 0.6633809953168787.
[I 2026-09-10 16:47:43,676] Trial 14 finished with value: 0.6717049716097456 and parameters: {'C': 0.0019224864168579348, 'l1_ratio': 0.06580418880357686}. Best is trial 1 with value: 0.6633809953168787.
[I 2026-09-10 16:47:43,683] Trial 8 finished with value: 0.6633807407792764 and parameters: {'C': 0.2660616697413542, 'l1_ratio': 0.5915324425554268}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:43,688] Trial 15 finished with value: 0.6635745919640892 and parameters: {'C': 0.12340216576161478, 'l1_ratio': 0.7081676489180463}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:43,701] Trial 12 finished with value: 0.6646893007754503 and parameters: {'C': 1.352842127217931, 'l1_ratio': 0.1658156226511266}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:43,707] Trial 9 finished with value: 0.6644874329996243 and parameters: {'C': 1.110790505730342, 'l1_ratio': 0.3949195378083117}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,166] Trial 16 finished with value: 0.682846745697617 and parameters: {'C': 0.009154946052777444, 'l1_ratio': 0.9337528611174791}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,226] Trial 18 finished with value: 0.6924277491035127 and parameters: {'C': 0.006227440562119813, 'l1_ratio': 0.9306151374453071}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,255] Trial 17 finished with value: 0.6654840143119155 and parameters: {'C': 0.0027875692402271873, 'l1_ratio': 0.0059972305145888916}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,266] Trial 20 finished with value: 0.6647889854322206 and parameters: {'C': 6.146151335774151, 'l1_ratio': 0.9496174759321718}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,266] Trial 25 finished with value: 0.6656823763595596 and parameters: {'C': 0.0383709900280398, 'l1_ratio': 0.6568035487698093}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,276] Trial 23 finished with value: 0.6647213052039682 and parameters: {'C': 3.4109639061357346, 'l1_ratio': 0.697878100301018}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,287] Trial 22 finished with value: 0.664795471441116 and parameters: {'C': 5.06354079787445, 'l1_ratio': 0.6881440495371001}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,301] Trial 19 finished with value: 0.664793320240516 and parameters: {'C': 6.487173657768337, 'l1_ratio': 0.9823443174462444}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,349] Trial 29 finished with value: 0.6656858175836919 and parameters: {'C': 0.033892781475973875, 'l1_ratio': 0.678302027279994}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,350] Trial 21 finished with value: 0.6647446067605653 and parameters: {'C': 4.918531125293405, 'l1_ratio': 0.982765554566915}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,367] Trial 24 finished with value: 0.6656797957630278 and parameters: {'C': 0.03482322857373962, 'l1_ratio': 0.6631477117152705}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,378] Trial 26 finished with value: 0.665691164406754 and parameters: {'C': 0.04088151977198293, 'l1_ratio': 0.6636780595998206}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,379] Trial 27 finished with value: 0.6657120729145316 and parameters: {'C': 0.033007267763302046, 'l1_ratio': 0.710515423179121}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,408] Trial 28 finished with value: 0.6656781450233462 and parameters: {'C': 0.038550952226876635, 'l1_ratio': 0.6777083682614168}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,414] Trial 30 finished with value: 0.6664179306758208 and parameters: {'C': 0.023105213630513405, 'l1_ratio': 0.6612091516119385}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,467] Trial 31 finished with value: 0.6656881224180193 and parameters: {'C': 0.04156634257202771, 'l1_ratio': 0.6826657479674686}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,737] Trial 32 finished with value: 0.6647696876183475 and parameters: {'C': 4.129255492315749, 'l1_ratio': 0.6498168808902578}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,770] Trial 33 finished with value: 0.6656924083705945 and parameters: {'C': 0.032816171409813244, 'l1_ratio': 0.6562129052244674}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,777] Trial 34 finished with value: 0.6656774560346812 and parameters: {'C': 0.03486438308741807, 'l1_ratio': 0.6559120587266589}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,835] Trial 35 finished with value: 0.6639478994485911 and parameters: {'C': 0.11863645262378492, 'l1_ratio': 0.8169708414832305}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,877] Trial 37 finished with value: 0.6658572231364747 and parameters: {'C': 0.06338536364863007, 'l1_ratio': 0.8003222551427693}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,882] Trial 36 finished with value: 0.6638614755403268 and parameters: {'C': 0.12232691049719122, 'l1_ratio': 0.8179177226377168}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,886] Trial 39 finished with value: 0.6647945288899795 and parameters: {'C': 0.10027640761354938, 'l1_ratio': 0.8661086867273036}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,892] Trial 38 finished with value: 0.6643142537585808 and parameters: {'C': 0.10898406649258094, 'l1_ratio': 0.8414306939724145}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,905] Trial 40 finished with value: 0.6638026736510401 and parameters: {'C': 0.12738948557540533, 'l1_ratio': 0.8376286401252676}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,921] Trial 41 finished with value: 0.6635316314224153 and parameters: {'C': 0.1394829380463923, 'l1_ratio': 0.8149005774970536}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:44,933] Trial 42 finished with value: 0.6636510974421291 and parameters: {'C': 0.1340414773243267, 'l1_ratio': 0.8299160414442268}. Best is trial 8 with value: 0.6633807407792764.
[I 2026-09-10 16:47:45,011] Trial 45 finished with value: 0.663112284852258 and parameters: {'C': 0.20537673893097488, 'l1_ratio': 0.795007817212644}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,014] Trial 43 finished with value: 0.6637087669061987 and parameters: {'C': 0.1315912171936335, 'l1_ratio': 0.8351135638822393}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,017] Trial 44 finished with value: 0.6631286719984391 and parameters: {'C': 0.22181434998190397, 'l1_ratio': 0.8064068472083492}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,023] Trial 46 finished with value: 0.6631199837028874 and parameters: {'C': 0.19949446906142237, 'l1_ratio': 0.8246079780514507}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,061] Trial 47 finished with value: 0.6632166644618545 and parameters: {'C': 0.2714155249256301, 'l1_ratio': 0.8133161651462338}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,304] Trial 48 finished with value: 0.6631263574090778 and parameters: {'C': 0.22516377186514128, 'l1_ratio': 0.8186764289815721}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,313] Trial 50 finished with value: 0.6631243537997333 and parameters: {'C': 0.22742067062567017, 'l1_ratio': 0.826828851527547}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,343] Trial 49 finished with value: 0.6631594726271478 and parameters: {'C': 0.2369523498098864, 'l1_ratio': 0.808732582652762}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,422] Trial 51 finished with value: 0.6634875434696534 and parameters: {'C': 0.30186153612140215, 'l1_ratio': 0.546212214609183}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,441] Trial 56 finished with value: 0.6635631106915805 and parameters: {'C': 0.3462187707365123, 'l1_ratio': 0.5562995583325792}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,444] Trial 53 finished with value: 0.6635720593256331 and parameters: {'C': 0.3545476949173157, 'l1_ratio': 0.5646230230499618}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,461] Trial 54 finished with value: 0.6635639829737408 and parameters: {'C': 0.3260875877773209, 'l1_ratio': 0.5166309342801267}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,483] Trial 55 finished with value: 0.6634668379559658 and parameters: {'C': 0.2840170758311466, 'l1_ratio': 0.535466443673537}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,490] Trial 52 finished with value: 0.6636907809167779 and parameters: {'C': 0.28532154978432706, 'l1_ratio': 0.35285057515069973}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,528] Trial 58 finished with value: 0.6634934003742216 and parameters: {'C': 0.31767517434066095, 'l1_ratio': 0.5679118600425095}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,550] Trial 59 finished with value: 0.6636828646202968 and parameters: {'C': 0.42529663315483196, 'l1_ratio': 0.5875227998117428}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,558] Trial 57 finished with value: 0.663902773425278 and parameters: {'C': 0.5485361460358642, 'l1_ratio': 0.5592949555799973}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,570] Trial 60 finished with value: 0.6637360093159375 and parameters: {'C': 0.4520192547887047, 'l1_ratio': 0.583224070792985}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,614] Trial 61 finished with value: 0.6638070486009324 and parameters: {'C': 0.4672349746235995, 'l1_ratio': 0.540072443842899}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,655] Trial 62 finished with value: 0.6637502750821413 and parameters: {'C': 0.4416289347828885, 'l1_ratio': 0.5542545947713882}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,661] Trial 63 finished with value: 0.6638039938848939 and parameters: {'C': 0.4864886067162376, 'l1_ratio': 0.5719477700451819}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,893] Trial 65 finished with value: 0.6635811424829126 and parameters: {'C': 0.4646215134899372, 'l1_ratio': 0.7633957654211634}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,946] Trial 64 finished with value: 0.6637172275399561 and parameters: {'C': 0.550820732342877, 'l1_ratio': 0.7647839070434591}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:45,958] Trial 66 finished with value: 0.6637022960211082 and parameters: {'C': 0.5402005197723799, 'l1_ratio': 0.7629542988294481}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,010] Trial 68 finished with value: 0.6637199931511027 and parameters: {'C': 0.5578029894458485, 'l1_ratio': 0.7728314232273092}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,055] Trial 70 finished with value: 0.6637618848420811 and parameters: {'C': 0.5712738448525415, 'l1_ratio': 0.7481980926971219}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,059] Trial 67 finished with value: 0.6636583448721259 and parameters: {'C': 0.5121122786362784, 'l1_ratio': 0.7609395378770284}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,062] Trial 72 finished with value: 0.6637232136666787 and parameters: {'C': 0.5599668643195528, 'l1_ratio': 0.7731493639407563}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,090] Trial 74 finished with value: 0.6631251225562337 and parameters: {'C': 0.1955245317576745, 'l1_ratio': 0.7622827569070224}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,091] Trial 71 finished with value: 0.6639051999056974 and parameters: {'C': 0.6972856203163253, 'l1_ratio': 0.7610845638638419}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,097] Trial 73 finished with value: 0.6637979421741435 and parameters: {'C': 0.6035779969323624, 'l1_ratio': 0.7567664642202032}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,098] Trial 69 finished with value: 0.6641426623737997 and parameters: {'C': 0.975016752022832, 'l1_ratio': 0.7577747619892671}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,150] Trial 76 finished with value: 0.6631452963202502 and parameters: {'C': 0.18288261080255316, 'l1_ratio': 0.7683130432841475}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,164] Trial 75 finished with value: 0.6631264467358928 and parameters: {'C': 0.20462762123830625, 'l1_ratio': 0.76502158952984}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,187] Trial 77 finished with value: 0.6631408755536625 and parameters: {'C': 0.18393963686271025, 'l1_ratio': 0.7591740313912516}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,237] Trial 79 finished with value: 0.6640685599097057 and parameters: {'C': 0.8803919772109273, 'l1_ratio': 0.7658106664808519}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,278] Trial 78 finished with value: 0.6631301130265467 and parameters: {'C': 0.19060090074112318, 'l1_ratio': 0.7615186875836798}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,468] Trial 80 finished with value: 0.6631325629712923 and parameters: {'C': 0.1885743090904246, 'l1_ratio': 0.757431629057181}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,502] Trial 83 finished with value: 0.6632088745408146 and parameters: {'C': 0.18618286064881115, 'l1_ratio': 0.9112494239300973}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,519] Trial 81 finished with value: 0.6640278296395975 and parameters: {'C': 0.9413174891399906, 'l1_ratio': 0.9009399211795958}. Best is trial 45 with value: 0.663112284852258.
[I 2026-09-10 16:47:46,550] Trial 82 finished with value: 0.6630992723522057 and parameters: {'C': 0.21863705616539492, 'l1_ratio': 0.8946035693248049}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,609] Trial 85 finished with value: 0.6631941970176335 and parameters: {'C': 0.18693913626745193, 'l1_ratio': 0.8965870969507653}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,648] Trial 84 finished with value: 0.663111816371839 and parameters: {'C': 0.21029740912307895, 'l1_ratio': 0.8999302267938369}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,651] Trial 87 finished with value: 0.663255668298012 and parameters: {'C': 0.18004037129037492, 'l1_ratio': 0.9216693730627451}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,664] Trial 86 finished with value: 0.6631491122198804 and parameters: {'C': 0.19637325339139042, 'l1_ratio': 0.8950737479121881}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,678] Trial 90 finished with value: 0.6631017928988696 and parameters: {'C': 0.2160684823456927, 'l1_ratio': 0.8920266926725238}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,701] Trial 89 finished with value: 0.6631544553853542 and parameters: {'C': 0.19763091178575437, 'l1_ratio': 0.9140859643121355}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,707] Trial 92 finished with value: 0.6658825153875407 and parameters: {'C': 0.07558587653792159, 'l1_ratio': 0.8949936489343939}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,710] Trial 88 finished with value: 0.6631222913827244 and parameters: {'C': 0.20650949471958385, 'l1_ratio': 0.91157698562578}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,755] Trial 93 finished with value: 0.6631776665313843 and parameters: {'C': 0.19062923759157235, 'l1_ratio': 0.9019499198152889}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,770] Trial 91 finished with value: 0.6631879131233543 and parameters: {'C': 0.18520100531100162, 'l1_ratio': 0.8760760780553127}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,796] Trial 94 finished with value: 0.6658479715191603 and parameters: {'C': 0.06877016116195006, 'l1_ratio': 0.8924071409632846}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:46,838] Trial 95 finished with value: 0.6658008392304219 and parameters: {'C': 0.08063796058563191, 'l1_ratio': 0.893289575752018}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:47,007] Trial 98 finished with value: 0.6656999043971509 and parameters: {'C': 0.08128707921633595, 'l1_ratio': 0.8710097070000775}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:47,008] Trial 97 finished with value: 0.6656119722464106 and parameters: {'C': 0.08324919940158254, 'l1_ratio': 0.8691567149391285}. Best is trial 82 with value: 0.6630992723522057.
[I 2026-09-10 16:47:47,030] Trial 96 finished with value: 0.6657466879541526 and parameters: {'C': 0.08235105391613173, 'l1_ratio': 0.8961377520048894}. Best is trial 82 with value: 0.6630992723522057.

Best parameters: {'C': 0.24743444755863572, 'l1_ratio': 0.9667385149953265}

[I 2026-09-10 16:48:03,070] Trial 5 finished with value: 0.6927912340983152 and parameters: {'C': 0.001110351873470595, 'l1_ratio': 0.23974509068864247}. Best is trial 5 with value: 0.6927912340983152.
[I 2026-09-10 16:48:03,090] Trial 1 finished with value: 0.6676094165750066 and parameters: {'C': 9.277665183439364, 'l1_ratio': 0.0013018842157017652}. Best is trial 1 with value: 0.6676094165750066.
[I 2026-09-10 16:48:03,106] Trial 0 finished with value: 0.6671958691617543 and parameters: {'C': 0.08122595308726381, 'l1_ratio': 0.151202165900286}. Best is trial 0 with value: 0.6671958691617543.
[I 2026-09-10 16:48:03,106] Trial 3 finished with value: 0.6729045586830058 and parameters: {'C': 0.009183335766891253, 'l1_ratio': 0.3544131827277405}. Best is trial 0 with value: 0.6671958691617543.
[I 2026-09-10 16:48:03,123] Trial 13 finished with value: 0.6929420288499184 and parameters: {'C': 0.0011535627659548368, 'l1_ratio': 0.8317670972525409}. Best is trial 0 with value: 0.6671958691617543.
[I 2026-09-10 16:48:03,125] Trial 4 finished with value: 0.6691069254468016 and parameters: {'C': 0.023794434796658902, 'l1_ratio': 0.2954197961629367}. Best is trial 0 with value: 0.6671958691617543.
[I 2026-09-10 16:48:03,127] Trial 15 finished with value: 0.6675696527930814 and parameters: {'C': 4.302635142688758, 'l1_ratio': 0.8230269080602668}. Best is trial 0 with value: 0.6671958691617543.
[I 2026-09-10 16:48:03,127] Trial 2 finished with value: 0.6673769079014297 and parameters: {'C': 0.12150895764880791, 'l1_ratio': 0.6102304383621878}. Best is trial 0 with value: 0.6671958691617543.
[I 2026-09-10 16:48:03,142] Trial 12 finished with value: 0.6686393984419515 and parameters: {'C': 0.010705327239722482, 'l1_ratio': 0.09648792315534216}. Best is trial 0 with value: 0.6671958691617543.
[I 2026-09-10 16:48:03,151] Trial 7 finished with value: 0.6675394167215896 and parameters: {'C': 2.590815366355056, 'l1_ratio': 0.8312313921403699}. Best is trial 0 with value: 0.6671958691617543.
[I 2026-09-10 16:48:03,158] Trial 6 finished with value: 0.6673305959356645 and parameters: {'C': 0.2929396403305735, 'l1_ratio': 0.257301165232807}. Best is trial 0 with value: 0.6671958691617543.
[I 2026-09-10 16:48:03,188] Trial 8 finished with value: 0.6671639398808419 and parameters: {'C': 0.04568319757246413, 'l1_ratio': 0.036292637944631334}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,200] Trial 10 finished with value: 0.678464142424962 and parameters: {'C': 0.005333150944174718, 'l1_ratio': 0.40894009371157924}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,201] Trial 11 finished with value: 0.6905915689751535 and parameters: {'C': 0.0027190931712129988, 'l1_ratio': 0.3998845856513411}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,225] Trial 9 finished with value: 0.6673995637662419 and parameters: {'C': 0.10429933355205787, 'l1_ratio': 0.5257952726971002}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,265] Trial 14 finished with value: 0.6674755932043587 and parameters: {'C': 1.350480263315271, 'l1_ratio': 0.8335713909972112}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,691] Trial 19 finished with value: 0.6672462166770001 and parameters: {'C': 0.28608607418813914, 'l1_ratio': 0.886131369551125}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,725] Trial 16 finished with value: 0.6711344709113487 and parameters: {'C': 0.028526668902234275, 'l1_ratio': 0.6371674963615258}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,734] Trial 18 finished with value: 0.6675877017407139 and parameters: {'C': 5.51220409502772, 'l1_ratio': 0.5435053032165273}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,751] Trial 17 finished with value: 0.6676073660327105 and parameters: {'C': 9.84247410021544, 'l1_ratio': 0.12836042262219072}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,783] Trial 22 finished with value: 0.6672078452242106 and parameters: {'C': 0.06129638439962432, 'l1_ratio': 0.12267433889202105}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,789] Trial 20 finished with value: 0.6673376491704891 and parameters: {'C': 0.4463505988265969, 'l1_ratio': 0.5415691575826027}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,794] Trial 21 finished with value: 0.6673431905581082 and parameters: {'C': 0.41240866219877315, 'l1_ratio': 0.4509112926773244}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,816] Trial 23 finished with value: 0.6674477475959744 and parameters: {'C': 0.4423049244898176, 'l1_ratio': 0.11149990409044203}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,833] Trial 26 finished with value: 0.6672352451021114 and parameters: {'C': 0.04441417364728232, 'l1_ratio': 0.09185111414472395}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,837] Trial 25 finished with value: 0.6673193212430008 and parameters: {'C': 0.044128310815488465, 'l1_ratio': 0.13129358391403106}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,871] Trial 29 finished with value: 0.667263799944053 and parameters: {'C': 0.048515575389771845, 'l1_ratio': 0.12276338997841217}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,878] Trial 28 finished with value: 0.6673275761005264 and parameters: {'C': 0.04128422748635964, 'l1_ratio': 0.12207393393187371}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,881] Trial 31 finished with value: 0.667348180393431 and parameters: {'C': 0.041071221287426476, 'l1_ratio': 0.12866484249228646}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,893] Trial 24 finished with value: 0.6674802973552096 and parameters: {'C': 0.5668796876204049, 'l1_ratio': 0.10563276648466148}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,939] Trial 30 finished with value: 0.6672898514588829 and parameters: {'C': 0.04604688757524895, 'l1_ratio': 0.12621112397837417}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:03,942] Trial 27 finished with value: 0.6672601190079309 and parameters: {'C': 0.04725548142150967, 'l1_ratio': 0.11612212919598967}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:04,296] Trial 33 finished with value: 0.667238767391223 and parameters: {'C': 0.05730478272803886, 'l1_ratio': 0.13890081704909363}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:04,299] Trial 32 finished with value: 0.6672150864038286 and parameters: {'C': 0.05660010914234777, 'l1_ratio': 0.11532037808421547}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:04,299] Trial 34 finished with value: 0.6672918799863388 and parameters: {'C': 0.049459159448149326, 'l1_ratio': 0.1417523669654387}. Best is trial 8 with value: 0.6671639398808419.
[I 2026-09-10 16:48:04,350] Trial 35 finished with value: 0.6671487549877637 and parameters: {'C': 0.045777340326410475, 'l1_ratio': 0.010687316075284559}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,353] Trial 38 finished with value: 0.6671527898664973 and parameters: {'C': 0.04735959947772302, 'l1_ratio': 0.01735584295852555}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,411] Trial 39 finished with value: 0.6672012739584324 and parameters: {'C': 0.11165433462463469, 'l1_ratio': 0.1920042686578837}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,416] Trial 42 finished with value: 0.6672531885857238 and parameters: {'C': 0.11182552475861614, 'l1_ratio': 0.027264345319515153}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,417] Trial 37 finished with value: 0.6672311427709394 and parameters: {'C': 0.0601765260928987, 'l1_ratio': 0.14255036755323267}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,420] Trial 36 finished with value: 0.667246806845913 and parameters: {'C': 0.05482808577848389, 'l1_ratio': 0.13613344597784244}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,455] Trial 41 finished with value: 0.6672548013698463 and parameters: {'C': 0.11293522215243999, 'l1_ratio': 0.026464564818378014}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,462] Trial 40 finished with value: 0.6673045710440701 and parameters: {'C': 0.13876983809684096, 'l1_ratio': 0.006274615699031011}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,500] Trial 47 finished with value: 0.6672892729590844 and parameters: {'C': 0.12476401176302306, 'l1_ratio': 0.0017871814768080224}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,513] Trial 45 finished with value: 0.6672885827767493 and parameters: {'C': 0.1341515048273842, 'l1_ratio': 0.022344659825346752}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,549] Trial 46 finished with value: 0.6672637802014902 and parameters: {'C': 0.11903787839832634, 'l1_ratio': 0.026802051191793644}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,573] Trial 44 finished with value: 0.6673198570925596 and parameters: {'C': 0.1493291487729578, 'l1_ratio': 0.003251360828534111}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,586] Trial 43 finished with value: 0.6672695658723781 and parameters: {'C': 0.11408658086437605, 'l1_ratio': 0.007848714043078811}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,903] Trial 49 finished with value: 0.6672819482150052 and parameters: {'C': 0.12535824558948563, 'l1_ratio': 0.013896258424752825}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,914] Trial 48 finished with value: 0.6672982510930426 and parameters: {'C': 0.13187792487888547, 'l1_ratio': 0.0022319088974663004}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,932] Trial 52 finished with value: 0.6673160846663159 and parameters: {'C': 0.14733488835088882, 'l1_ratio': 0.004952525063598525}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:04,963] Trial 50 finished with value: 0.6672153765609159 and parameters: {'C': 0.14039429508481038, 'l1_ratio': 0.21736709867949694}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,011] Trial 51 finished with value: 0.667295571968249 and parameters: {'C': 0.1351760509240856, 'l1_ratio': 0.01332131231770565}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,033] Trial 54 finished with value: 0.6671670627654921 and parameters: {'C': 0.012932882497071621, 'l1_ratio': 0.003055896819231012}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,045] Trial 56 finished with value: 0.6693280755497087 and parameters: {'C': 0.016095858827265115, 'l1_ratio': 0.21244114274662787}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,047] Trial 53 finished with value: 0.667172227031061 and parameters: {'C': 0.013852016804373563, 'l1_ratio': 0.004582119764034692}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,070] Trial 55 finished with value: 0.6691625108820822 and parameters: {'C': 0.018015554038535133, 'l1_ratio': 0.22478232104198306}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,104] Trial 59 finished with value: 0.6690683694527568 and parameters: {'C': 0.01757812083599204, 'l1_ratio': 0.21034868467285422}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,111] Trial 57 finished with value: 0.6701665876240416 and parameters: {'C': 0.013063248998162483, 'l1_ratio': 0.21831629878513867}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,118] Trial 58 finished with value: 0.6698973972354226 and parameters: {'C': 0.014162302971450358, 'l1_ratio': 0.22146796329232865}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,124] Trial 60 finished with value: 0.6694581122208978 and parameters: {'C': 0.015203523557524244, 'l1_ratio': 0.20923780180199603}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,146] Trial 62 finished with value: 0.6696667537798362 and parameters: {'C': 0.01439808018711696, 'l1_ratio': 0.21100756393481496}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,174] Trial 61 finished with value: 0.6701133688722264 and parameters: {'C': 0.013282588572642553, 'l1_ratio': 0.21929913604348525}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,209] Trial 63 finished with value: 0.6694022085529281 and parameters: {'C': 0.015560004412329716, 'l1_ratio': 0.2104353376317487}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,476] Trial 66 finished with value: 0.6706824621520839 and parameters: {'C': 0.010282058353234346, 'l1_ratio': 0.1890807882115151}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,505] Trial 64 finished with value: 0.6697781448172899 and parameters: {'C': 0.014690728043435186, 'l1_ratio': 0.22299753850826948}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,522] Trial 65 finished with value: 0.670694860405116 and parameters: {'C': 0.011154543649666462, 'l1_ratio': 0.20742732894522953}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,578] Trial 69 finished with value: 0.675891829410436 and parameters: {'C': 0.0051316343033372454, 'l1_ratio': 0.3054001993235528}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,579] Trial 67 finished with value: 0.6690135572035417 and parameters: {'C': 0.017197558845591886, 'l1_ratio': 0.20043877936787047}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,602] Trial 68 finished with value: 0.6690119650668482 and parameters: {'C': 0.015896826433326253, 'l1_ratio': 0.184138052670677}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,648] Trial 71 finished with value: 0.6725530493789651 and parameters: {'C': 0.008579087332103991, 'l1_ratio': 0.294770582517392}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,654] Trial 72 finished with value: 0.6696549837063369 and parameters: {'C': 0.005264294863753984, 'l1_ratio': 0.06409970762210432}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,659] Trial 70 finished with value: 0.668850581287084 and parameters: {'C': 0.00571051805933149, 'l1_ratio': 0.049352480229122885}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,709] Trial 74 finished with value: 0.6695014915154994 and parameters: {'C': 0.005754384219348161, 'l1_ratio': 0.0680790380175478}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,711] Trial 73 finished with value: 0.6694749295975424 and parameters: {'C': 0.005197801713017828, 'l1_ratio': 0.058661910692412896}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,714] Trial 76 finished with value: 0.6689805761202436 and parameters: {'C': 0.006608399768605637, 'l1_ratio': 0.06494257617748682}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,755] Trial 77 finished with value: 0.6673360523351406 and parameters: {'C': 0.028285064351696858, 'l1_ratio': 0.0707766498886212}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,781] Trial 75 finished with value: 0.6692804660955529 and parameters: {'C': 0.0065888913631898015, 'l1_ratio': 0.07415197801015917}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,784] Trial 79 finished with value: 0.6673754752114217 and parameters: {'C': 0.025067071518310433, 'l1_ratio': 0.06583087042672908}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:05,805] Trial 78 finished with value: 0.6691262010667371 and parameters: {'C': 0.005943186489013036, 'l1_ratio': 0.06053036647468191}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,117] Trial 80 finished with value: 0.6747582450095926 and parameters: {'C': 0.005568116097550782, 'l1_ratio': 0.2863954409395649}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,124] Trial 81 finished with value: 0.6702317105119511 and parameters: {'C': 0.004230555664149025, 'l1_ratio': 0.05808928155992374}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,161] Trial 83 finished with value: 0.6671813049709192 and parameters: {'C': 0.07813343100337936, 'l1_ratio': 0.06623151959406588}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,164] Trial 82 finished with value: 0.6691267810134269 and parameters: {'C': 0.006547530505433702, 'l1_ratio': 0.06879106282310994}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,193] Trial 84 finished with value: 0.6673488126327561 and parameters: {'C': 0.026842656271843676, 'l1_ratio': 0.06832245997272493}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,237] Trial 85 finished with value: 0.6672906348771072 and parameters: {'C': 0.02904652787002988, 'l1_ratio': 0.06198550951095693}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,254] Trial 88 finished with value: 0.667337569444399 and parameters: {'C': 0.02931623820307911, 'l1_ratio': 0.07476334788996801}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,301] Trial 89 finished with value: 0.6679572478631115 and parameters: {'C': 0.02833726385158485, 'l1_ratio': 0.16893311036514222}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,322] Trial 86 finished with value: 0.6671817201671073 and parameters: {'C': 0.07797022437975128, 'l1_ratio': 0.06281606358752392}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,323] Trial 91 finished with value: 0.6672049096542395 and parameters: {'C': 0.07965393388214098, 'l1_ratio': 0.17076090152018739}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,328] Trial 90 finished with value: 0.6671837437077377 and parameters: {'C': 0.08082426238127452, 'l1_ratio': 0.09067233631138177}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,331] Trial 87 finished with value: 0.6675251561642738 and parameters: {'C': 0.024115520374893586, 'l1_ratio': 0.08305269318172398}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,332] Trial 92 finished with value: 0.6671848618557898 and parameters: {'C': 0.08373759530941972, 'l1_ratio': 0.096323454832805}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,332] Trial 93 finished with value: 0.6672023599804094 and parameters: {'C': 0.07824344875761555, 'l1_ratio': 0.16095467767284802}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,402] Trial 95 finished with value: 0.6672030646304675 and parameters: {'C': 0.08430138987806696, 'l1_ratio': 0.17703228323369163}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,406] Trial 94 finished with value: 0.6672032020703001 and parameters: {'C': 0.08022723771269288, 'l1_ratio': 0.16651107443506802}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,673] Trial 96 finished with value: 0.6672026614378389 and parameters: {'C': 0.07825837719205447, 'l1_ratio': 0.1609195744868246}. Best is trial 35 with value: 0.6671487549877637.
[I 2026-09-10 16:48:06,695] Trial 97 finished with value: 0.6671983567825996 and parameters: {'C': 0.08519705182929296, 'l1_ratio': 0.1667698044720338}. Best is trial 35 with value: 0.6671487549877637.

Best parameters: {'C': 0.02073176357863719, 'l1_ratio': 0.0003489405574088563}

[I 2026-09-10 16:48:22,650] Trial 0 finished with value: 0.6928221495435286 and parameters: {'C': 0.0018007805152572736, 'l1_ratio': 0.9220013675683362}. Best is trial 0 with value: 0.6928221495435286.
[I 2026-09-10 16:48:22,724] Trial 3 finished with value: 0.6736167877807719 and parameters: {'C': 0.015517574392341173, 'l1_ratio': 0.8119489181123559}. Best is trial 3 with value: 0.6736167877807719.
[I 2026-09-10 16:48:22,806] Trial 7 finished with value: 0.6704502315738186 and parameters: {'C': 0.029258473128019394, 'l1_ratio': 0.624024766597831}. Best is trial 7 with value: 0.6704502315738186.
[I 2026-09-10 16:48:22,832] Trial 14 finished with value: 0.67788283430603 and parameters: {'C': 0.012005690773057454, 'l1_ratio': 0.9380096501805272}. Best is trial 7 with value: 0.6704502315738186.
[I 2026-09-10 16:48:22,849] Trial 6 finished with value: 0.6710279906067531 and parameters: {'C': 0.015979037281280254, 'l1_ratio': 0.42153871598388337}. Best is trial 7 with value: 0.6704502315738186.
[I 2026-09-10 16:48:22,850] Trial 4 finished with value: 0.6645140002109577 and parameters: {'C': 3.6849662978546918, 'l1_ratio': 0.9376432120487439}. Best is trial 4 with value: 0.6645140002109577.
[I 2026-09-10 16:48:22,868] Trial 10 finished with value: 0.6642334281546279 and parameters: {'C': 0.3874576298795481, 'l1_ratio': 0.681142582839975}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:22,878] Trial 2 finished with value: 0.6645157741411466 and parameters: {'C': 2.0490031514683475, 'l1_ratio': 0.235717270225142}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:22,881] Trial 11 finished with value: 0.664568132159087 and parameters: {'C': 7.2674206168196385, 'l1_ratio': 0.14286143492018177}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:22,882] Trial 5 finished with value: 0.6644027017247389 and parameters: {'C': 1.2373563338614926, 'l1_ratio': 0.9257885539047485}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:22,887] Trial 12 finished with value: 0.6645001271008926 and parameters: {'C': 1.7632765119104745, 'l1_ratio': 0.3020638162681867}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:22,888] Trial 9 finished with value: 0.6707602288667869 and parameters: {'C': 0.013684924008631931, 'l1_ratio': 0.32643520559904526}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:22,893] Trial 8 finished with value: 0.6645318714008852 and parameters: {'C': 3.9724590847030368, 'l1_ratio': 0.599321773032065}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:22,894] Trial 1 finished with value: 0.6644980250959867 and parameters: {'C': 2.850563644277819, 'l1_ratio': 0.8922985804328106}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:22,900] Trial 13 finished with value: 0.6644150862115116 and parameters: {'C': 1.14395673321956, 'l1_ratio': 0.6923719367144802}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:22,962] Trial 15 finished with value: 0.6644921810406759 and parameters: {'C': 2.68203670543252, 'l1_ratio': 0.9097688847158512}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:23,292] Trial 16 finished with value: 0.6644613413105382 and parameters: {'C': 0.8907543901749928, 'l1_ratio': 0.10662933028877586}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:23,344] Trial 17 finished with value: 0.6645705824995441 and parameters: {'C': 7.828694828756066, 'l1_ratio': 0.08544130732162347}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:23,407] Trial 18 finished with value: 0.6643384323245457 and parameters: {'C': 0.37484679065333054, 'l1_ratio': 0.08666703158561684}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:23,416] Trial 19 finished with value: 0.6700134269802158 and parameters: {'C': 0.01987296405170313, 'l1_ratio': 0.37620913072909734}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:23,447] Trial 20 finished with value: 0.6642956081470077 and parameters: {'C': 0.6773957052749697, 'l1_ratio': 0.9766405804914587}. Best is trial 10 with value: 0.6642334281546279.
[I 2026-09-10 16:48:23,457] Trial 21 finished with value: 0.6641937439910379 and parameters: {'C': 0.24751697017162583, 'l1_ratio': 0.5434189832963188}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,471] Trial 24 finished with value: 0.6642284638759796 and parameters: {'C': 0.38735780254830227, 'l1_ratio': 0.7474812409621185}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,473] Trial 22 finished with value: 0.6642098752497649 and parameters: {'C': 0.31883568215665037, 'l1_ratio': 0.7301922221075516}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,485] Trial 23 finished with value: 0.664216079133646 and parameters: {'C': 0.34671070165790074, 'l1_ratio': 0.7546548056962511}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,491] Trial 25 finished with value: 0.6642101751595926 and parameters: {'C': 0.31803924710766046, 'l1_ratio': 0.7511431010276364}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,510] Trial 26 finished with value: 0.6642232806389049 and parameters: {'C': 0.3675900599623216, 'l1_ratio': 0.7327822024877996}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,566] Trial 27 finished with value: 0.6642347772466891 and parameters: {'C': 0.4043934687519846, 'l1_ratio': 0.7425834734458779}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,580] Trial 31 finished with value: 0.6642209461316549 and parameters: {'C': 0.2609855113241107, 'l1_ratio': 0.7641282842163732}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,596] Trial 29 finished with value: 0.6642250892293914 and parameters: {'C': 0.3760624905717694, 'l1_ratio': 0.7448518718322439}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,605] Trial 30 finished with value: 0.664209913956193 and parameters: {'C': 0.3177934863684953, 'l1_ratio': 0.7476892176500658}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,629] Trial 28 finished with value: 0.664215405290103 and parameters: {'C': 0.34085962370267486, 'l1_ratio': 0.723995092799864}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,859] Trial 32 finished with value: 0.6642696425114988 and parameters: {'C': 0.22198305115028188, 'l1_ratio': 0.7534023058860673}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,954] Trial 33 finished with value: 0.6642104475005778 and parameters: {'C': 0.314176158231806, 'l1_ratio': 0.7821151608868849}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,982] Trial 34 finished with value: 0.6642231452240801 and parameters: {'C': 0.3154612761591963, 'l1_ratio': 0.4801446180727599}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,986] Trial 36 finished with value: 0.664194712417661 and parameters: {'C': 0.20009826670720857, 'l1_ratio': 0.5088169147822155}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:23,996] Trial 35 finished with value: 0.6643012434880492 and parameters: {'C': 0.2711838979622829, 'l1_ratio': 0.00705823895584913}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,011] Trial 37 finished with value: 0.6646166742698643 and parameters: {'C': 0.10941130969171052, 'l1_ratio': 0.5146797049536173}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,057] Trial 38 finished with value: 0.6649400694705998 and parameters: {'C': 0.08993711572439203, 'l1_ratio': 0.5074841122288212}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,076] Trial 39 finished with value: 0.6651449036829937 and parameters: {'C': 0.08364211593322639, 'l1_ratio': 0.517475153508264}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,080] Trial 42 finished with value: 0.6646321468955174 and parameters: {'C': 0.11356867466315879, 'l1_ratio': 0.5469750137584799}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,084] Trial 40 finished with value: 0.6644026229516132 and parameters: {'C': 0.12755726960529398, 'l1_ratio': 0.4943161113422028}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,112] Trial 41 finished with value: 0.6647034841306092 and parameters: {'C': 0.10159153206766325, 'l1_ratio': 0.5026979955154843}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,123] Trial 43 finished with value: 0.6645647267468715 and parameters: {'C': 0.11415549216301239, 'l1_ratio': 0.5179023550666821}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,164] Trial 45 finished with value: 0.6645902601774005 and parameters: {'C': 0.10948031878967432, 'l1_ratio': 0.5030279432221488}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,171] Trial 47 finished with value: 0.6648503994262935 and parameters: {'C': 0.09774492661199596, 'l1_ratio': 0.5329241849079147}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,184] Trial 44 finished with value: 0.6646328724238194 and parameters: {'C': 0.10150917309265749, 'l1_ratio': 0.4745000392531681}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,216] Trial 46 finished with value: 0.6645905180516272 and parameters: {'C': 0.11396806441100295, 'l1_ratio': 0.529495090483596}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,421] Trial 48 finished with value: 0.664813811565838 and parameters: {'C': 0.10676694927846431, 'l1_ratio': 0.5806251838188375}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,489] Trial 50 finished with value: 0.6645820789736925 and parameters: {'C': 0.12110581539791014, 'l1_ratio': 0.5672442712243821}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,542] Trial 49 finished with value: 0.6647760431181828 and parameters: {'C': 0.10507164822757409, 'l1_ratio': 0.5546057874800226}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,565] Trial 52 finished with value: 0.6649872950836087 and parameters: {'C': 0.0953937511522803, 'l1_ratio': 0.561280431115786}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,578] Trial 51 finished with value: 0.6646629196353915 and parameters: {'C': 0.11316814491239369, 'l1_ratio': 0.5581905312491112}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,620] Trial 53 finished with value: 0.6653622427962482 and parameters: {'C': 0.08269788357439942, 'l1_ratio': 0.5650912546585614}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,645] Trial 54 finished with value: 0.6644686815331036 and parameters: {'C': 0.14393417149694313, 'l1_ratio': 0.62536542194822}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,672] Trial 56 finished with value: 0.6704368031406743 and parameters: {'C': 0.03975279793451937, 'l1_ratio': 0.8408226944897006}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,675] Trial 58 finished with value: 0.6704448048264953 and parameters: {'C': 0.03908106259910964, 'l1_ratio': 0.8290993251475949}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,680] Trial 59 finished with value: 0.6696806420359703 and parameters: {'C': 0.04899318610989505, 'l1_ratio': 0.8582360427272876}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,690] Trial 61 finished with value: 0.6704927771607198 and parameters: {'C': 0.03956854540644913, 'l1_ratio': 0.8537265959301991}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,698] Trial 57 finished with value: 0.6697709409004042 and parameters: {'C': 0.04794156700764748, 'l1_ratio': 0.8596387471297082}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,699] Trial 55 finished with value: 0.6647075506747645 and parameters: {'C': 0.155190473290575, 'l1_ratio': 0.8456440282183122}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,773] Trial 60 finished with value: 0.6643071749120302 and parameters: {'C': 0.6718461362028401, 'l1_ratio': 0.8596165867698772}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,780] Trial 62 finished with value: 0.6643063079619616 and parameters: {'C': 0.6503570967048912, 'l1_ratio': 0.8186031586097737}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,805] Trial 63 finished with value: 0.6695690507384245 and parameters: {'C': 0.04948492681261489, 'l1_ratio': 0.8416352679620897}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:24,994] Trial 64 finished with value: 0.6701759390571607 and parameters: {'C': 0.04331521789346826, 'l1_ratio': 0.8579116275914788}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,037] Trial 65 finished with value: 0.6696347105611969 and parameters: {'C': 0.04955009926719062, 'l1_ratio': 0.8575731084805038}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,129] Trial 66 finished with value: 0.6704425692220966 and parameters: {'C': 0.040802029496440954, 'l1_ratio': 0.864567662193835}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,160] Trial 67 finished with value: 0.6685063865829507 and parameters: {'C': 0.05917233739029451, 'l1_ratio': 0.8253429074354485}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,173] Trial 70 finished with value: 0.6689210595171307 and parameters: {'C': 0.05577419104715161, 'l1_ratio': 0.8397651307492372}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,198] Trial 68 finished with value: 0.6643305506049626 and parameters: {'C': 0.7584729892859979, 'l1_ratio': 0.8461070999017789}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,207] Trial 69 finished with value: 0.669996981893189 and parameters: {'C': 0.044688997301092735, 'l1_ratio': 0.8471152479818141}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,255] Trial 72 finished with value: 0.664326216028847 and parameters: {'C': 0.6507543202430802, 'l1_ratio': 0.6652631580138781}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,310] Trial 71 finished with value: 0.6643261394072052 and parameters: {'C': 0.6361871777141855, 'l1_ratio': 0.6364938255692651}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,345] Trial 74 finished with value: 0.6643015264445613 and parameters: {'C': 0.5780550656393565, 'l1_ratio': 0.6877931287151912}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,347] Trial 75 finished with value: 0.6643015289252181 and parameters: {'C': 0.5773172708853842, 'l1_ratio': 0.685453186140213}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,362] Trial 73 finished with value: 0.6643184273654901 and parameters: {'C': 0.6221935511541208, 'l1_ratio': 0.6623036275318633}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,363] Trial 76 finished with value: 0.6643084567075628 and parameters: {'C': 0.5938933467805944, 'l1_ratio': 0.6724663519495997}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,386] Trial 77 finished with value: 0.66433438597272 and parameters: {'C': 0.6821059297060948, 'l1_ratio': 0.6684744802908151}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,397] Trial 78 finished with value: 0.6642813544118871 and parameters: {'C': 0.2001405942015242, 'l1_ratio': 0.6894852611025111}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,416] Trial 79 finished with value: 0.6642962781929023 and parameters: {'C': 0.1890520210473732, 'l1_ratio': 0.6676994188301177}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,608] Trial 81 finished with value: 0.6643156558250171 and parameters: {'C': 0.1800431734756356, 'l1_ratio': 0.6556195485384639}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,648] Trial 80 finished with value: 0.6642696449023037 and parameters: {'C': 0.20064427737408153, 'l1_ratio': 0.6724764062711533}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,761] Trial 82 finished with value: 0.664282884179559 and parameters: {'C': 0.1947488649869918, 'l1_ratio': 0.6717786666994908}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,767] Trial 84 finished with value: 0.664296497214539 and parameters: {'C': 0.5544014973329315, 'l1_ratio': 0.6673061770990356}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,777] Trial 85 finished with value: 0.664279994853891 and parameters: {'C': 0.1996371291168944, 'l1_ratio': 0.6856474997202053}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,787] Trial 83 finished with value: 0.6644686176637687 and parameters: {'C': 1.75402360649921, 'l1_ratio': 0.674647058928452}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,816] Trial 87 finished with value: 0.6642587861333853 and parameters: {'C': 0.4865179584018247, 'l1_ratio': 0.7855046616688314}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,862] Trial 86 finished with value: 0.6642547517024523 and parameters: {'C': 0.20923402973227656, 'l1_ratio': 0.6795295976368132}. Best is trial 21 with value: 0.6641937439910379.
[I 2026-09-10 16:48:25,864] Trial 88 finished with value: 0.6641810614245411 and parameters: {'C': 0.19849655308248734, 'l1_ratio': 0.4096536974878401}. Best is trial 88 with value: 0.6641810614245411.
[I 2026-09-10 16:48:25,901] Trial 89 finished with value: 0.6644441859811068 and parameters: {'C': 1.5261726140604488, 'l1_ratio': 0.7805606598378132}. Best is trial 88 with value: 0.6641810614245411.
[I 2026-09-10 16:48:25,905] Trial 91 finished with value: 0.664355744481757 and parameters: {'C': 0.18195827457825997, 'l1_ratio': 0.7111876134458698}. Best is trial 88 with value: 0.6641810614245411.
[I 2026-09-10 16:48:25,909] Trial 90 finished with value: 0.6643135993734212 and parameters: {'C': 0.2123668886015187, 'l1_ratio': 0.7884288053632293}. Best is trial 88 with value: 0.6641810614245411.
[I 2026-09-10 16:48:25,963] Trial 92 finished with value: 0.6643687331742083 and parameters: {'C': 0.19651483875034584, 'l1_ratio': 0.7930787334392103}. Best is trial 88 with value: 0.6641810614245411.
[I 2026-09-10 16:48:25,974] Trial 93 finished with value: 0.6643592697789388 and parameters: {'C': 0.1976527848646128, 'l1_ratio': 0.7866794444593005}. Best is trial 88 with value: 0.6641810614245411.
[I 2026-09-10 16:48:26,016] Trial 95 finished with value: 0.6644048589743121 and parameters: {'C': 1.1352179111370215, 'l1_ratio': 0.7763230855567823}. Best is trial 88 with value: 0.6641810614245411.
[I 2026-09-10 16:48:26,022] Trial 94 finished with value: 0.6643938403944929 and parameters: {'C': 1.0567861746181628, 'l1_ratio': 0.7793242820704773}. Best is trial 88 with value: 0.6641810614245411.
[I 2026-09-10 16:48:26,195] Trial 96 finished with value: 0.6642284096198938 and parameters: {'C': 0.264489771513086, 'l1_ratio': 0.7982578209363494}. Best is trial 88 with value: 0.6641810614245411.
[I 2026-09-10 16:48:26,230] Trial 97 finished with value: 0.6642229611640615 and parameters: {'C': 0.25922996022953276, 'l1_ratio': 0.766001483773026}. Best is trial 88 with value: 0.6641810614245411.
[I 2026-09-10 16:48:26,335] Trial 99 finished with value: 0.6642112316974593 and parameters: {'C': 0.28418765425561865, 'l1_ratio': 0.7799657004860946}. Best is trial 88 with value: 0.6641810614245411.

Best parameters: {'C': 0.06998262079013826, 'l1_ratio': 0.0005731264604019856}

[I 2026-09-10 16:48:42,109] Trial 15 finished with value: 0.692691885471349 and parameters: {'C': 0.0010217410424170983, 'l1_ratio': 0.8836347032427817}. Best is trial 15 with value: 0.692691885471349.
[I 2026-09-10 16:48:42,122] Trial 0 finished with value: 0.6926724009479296 and parameters: {'C': 0.002120223508137983, 'l1_ratio': 0.8243045550043124}. Best is trial 0 with value: 0.6926724009479296.
[I 2026-09-10 16:48:42,142] Trial 14 finished with value: 0.6926730793377975 and parameters: {'C': 0.001787511662367727, 'l1_ratio': 0.49370918672063324}. Best is trial 0 with value: 0.6926724009479296.
[I 2026-09-10 16:48:42,175] Trial 1 finished with value: 0.6926711065736408 and parameters: {'C': 0.00326374775338201, 'l1_ratio': 0.953722535328122}. Best is trial 1 with value: 0.6926711065736408.
[I 2026-09-10 16:48:42,234] Trial 4 finished with value: 0.6822080081986573 and parameters: {'C': 0.00843104298880105, 'l1_ratio': 0.9719845519877278}. Best is trial 4 with value: 0.6822080081986573.
[I 2026-09-10 16:48:42,254] Trial 9 finished with value: 0.6926710524589349 and parameters: {'C': 0.002823656768823761, 'l1_ratio': 0.771193419620661}. Best is trial 4 with value: 0.6822080081986573.
[I 2026-09-10 16:48:42,461] Trial 6 finished with value: 0.680466618884875 and parameters: {'C': 0.007508578573403181, 'l1_ratio': 0.7591539626786067}. Best is trial 6 with value: 0.680466618884875.
[I 2026-09-10 16:48:42,522] Trial 13 finished with value: 0.672416917725149 and parameters: {'C': 0.0804401595167023, 'l1_ratio': 0.2861737696386979}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,563] Trial 17 finished with value: 0.6817524654542935 and parameters: {'C': 0.004642796017239687, 'l1_ratio': 0.5072368448673733}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,589] Trial 5 finished with value: 0.6730284773236835 and parameters: {'C': 0.4716125930626086, 'l1_ratio': 0.9163846540448504}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,610] Trial 7 finished with value: 0.673072263664363 and parameters: {'C': 0.17628219198447945, 'l1_ratio': 0.2555672740382525}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,650] Trial 3 finished with value: 0.6736360756368339 and parameters: {'C': 0.893169559249998, 'l1_ratio': 0.10041088490937322}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,681] Trial 10 finished with value: 0.6729741379945761 and parameters: {'C': 0.083937286918835, 'l1_ratio': 0.10860064299299432}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,690] Trial 11 finished with value: 0.6735776637013376 and parameters: {'C': 0.34377369824131376, 'l1_ratio': 0.024639232794324784}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,755] Trial 12 finished with value: 0.6736509343602397 and parameters: {'C': 2.3332465548946995, 'l1_ratio': 0.36481502903262786}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,761] Trial 18 finished with value: 0.6859163615278119 and parameters: {'C': 0.0038726045945770117, 'l1_ratio': 0.5749762642895629}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,822] Trial 2 finished with value: 0.6736417782417327 and parameters: {'C': 2.360875498824052, 'l1_ratio': 0.44742091672898}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,842] Trial 8 finished with value: 0.6737024185084662 and parameters: {'C': 6.321494719147873, 'l1_ratio': 0.25188103558731134}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:42,919] Trial 20 finished with value: 0.67248914992613 and parameters: {'C': 0.23452910920499992, 'l1_ratio': 0.8855525844046496}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:43,013] Trial 16 finished with value: 0.6734565222296014 and parameters: {'C': 1.2383381315407302, 'l1_ratio': 0.8781088941764604}. Best is trial 13 with value: 0.672416917725149.
[I 2026-09-10 16:48:43,098] Trial 22 finished with value: 0.6722323621515578 and parameters: {'C': 0.017459285324491147, 'l1_ratio': 0.589819224171697}. Best is trial 22 with value: 0.6722323621515578.
[I 2026-09-10 16:48:43,177] Trial 19 finished with value: 0.6713912722588016 and parameters: {'C': 0.043711690583301814, 'l1_ratio': 0.41614252786315864}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,189] Trial 21 finished with value: 0.6736367635160513 and parameters: {'C': 4.225638964137265, 'l1_ratio': 0.9520549282543501}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,349] Trial 27 finished with value: 0.6719669454266152 and parameters: {'C': 0.0912412585438867, 'l1_ratio': 0.5299355690347942}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,388] Trial 23 finished with value: 0.6736630127135086 and parameters: {'C': 5.1727044508245195, 'l1_ratio': 0.8048729803364945}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,434] Trial 26 finished with value: 0.6736613540275155 and parameters: {'C': 0.8950609296146791, 'l1_ratio': 0.03233159675907027}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,439] Trial 29 finished with value: 0.6721051400547818 and parameters: {'C': 0.05261108497324636, 'l1_ratio': 0.25334547740201696}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,469] Trial 24 finished with value: 0.6735802667728237 and parameters: {'C': 2.595042207483128, 'l1_ratio': 0.9792472850757657}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,495] Trial 31 finished with value: 0.6725193658845573 and parameters: {'C': 0.06817115561719202, 'l1_ratio': 0.20279552971574777}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,545] Trial 33 finished with value: 0.6723686930423071 and parameters: {'C': 0.0511401335423525, 'l1_ratio': 0.17506185802816004}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,569] Trial 30 finished with value: 0.6721943806424948 and parameters: {'C': 0.04803036082189862, 'l1_ratio': 0.2055306840913234}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,635] Trial 25 finished with value: 0.6737123491752928 and parameters: {'C': 5.50233016959835, 'l1_ratio': 0.043282949988457664}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,637] Trial 28 finished with value: 0.6721803451571665 and parameters: {'C': 0.060063355467574936, 'l1_ratio': 0.2730884973601075}. Best is trial 19 with value: 0.6713912722588016.
[I 2026-09-10 16:48:43,653] Trial 34 finished with value: 0.6712119006406437 and parameters: {'C': 0.05409844367303536, 'l1_ratio': 0.6427666299099895}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:43,717] Trial 32 finished with value: 0.6722967199201244 and parameters: {'C': 0.054535263875852516, 'l1_ratio': 0.2115801068293672}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:43,868] Trial 35 finished with value: 0.6717903435890227 and parameters: {'C': 0.028324978153374706, 'l1_ratio': 0.6830226686982104}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:43,885] Trial 36 finished with value: 0.6715931298780318 and parameters: {'C': 0.03186473690777224, 'l1_ratio': 0.667850746278194}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,033] Trial 39 finished with value: 0.6718596924514175 and parameters: {'C': 0.022405364712360175, 'l1_ratio': 0.6301368180400262}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,041] Trial 37 finished with value: 0.6712486694053222 and parameters: {'C': 0.03826512264638015, 'l1_ratio': 0.641105324623946}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,055] Trial 38 finished with value: 0.6717485120972337 and parameters: {'C': 0.02847129071347998, 'l1_ratio': 0.6550603272569524}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,208] Trial 42 finished with value: 0.6712497637786617 and parameters: {'C': 0.03009411272052981, 'l1_ratio': 0.3623273559433814}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,227] Trial 46 finished with value: 0.6712471969476226 and parameters: {'C': 0.025592502045471765, 'l1_ratio': 0.36370472688291483}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,281] Trial 40 finished with value: 0.6715384197686725 and parameters: {'C': 0.03194820266278085, 'l1_ratio': 0.6484581458470398}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,299] Trial 45 finished with value: 0.6718296567978543 and parameters: {'C': 0.02472516748821848, 'l1_ratio': 0.664183527203177}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,315] Trial 44 finished with value: 0.6717692285154601 and parameters: {'C': 0.028316560232961103, 'l1_ratio': 0.6604260295077896}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,345] Trial 43 finished with value: 0.6716330134761452 and parameters: {'C': 0.03185206117948975, 'l1_ratio': 0.6870450163293145}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,367] Trial 47 finished with value: 0.6712703094954443 and parameters: {'C': 0.023839121251112667, 'l1_ratio': 0.3648596318082613}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,388] Trial 41 finished with value: 0.6717836413256103 and parameters: {'C': 0.028323940241659344, 'l1_ratio': 0.6679369189710471}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,402] Trial 48 finished with value: 0.6713265724594742 and parameters: {'C': 0.02271385365413072, 'l1_ratio': 0.37728896310202775}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,411] Trial 49 finished with value: 0.6719105489355528 and parameters: {'C': 0.023452575507576696, 'l1_ratio': 0.6778603151187047}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,446] Trial 50 finished with value: 0.6718742055197546 and parameters: {'C': 0.02355750600252879, 'l1_ratio': 0.6644022016807877}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,640] Trial 51 finished with value: 0.6717833062620786 and parameters: {'C': 0.02673537550580558, 'l1_ratio': 0.658317310920658}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,686] Trial 53 finished with value: 0.6745147861762305 and parameters: {'C': 0.012725749219793102, 'l1_ratio': 0.7201438044213477}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,689] Trial 52 finished with value: 0.6718366952995137 and parameters: {'C': 0.025512826825432062, 'l1_ratio': 0.6854924754116275}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,817] Trial 56 finished with value: 0.6719878660821701 and parameters: {'C': 0.013829203593632542, 'l1_ratio': 0.4283650563185889}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,875] Trial 57 finished with value: 0.6719575846760203 and parameters: {'C': 0.012581668874668531, 'l1_ratio': 0.38457799871968196}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,922] Trial 55 finished with value: 0.6719022325897868 and parameters: {'C': 0.01348635500416346, 'l1_ratio': 0.40201452904877594}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:44,932] Trial 54 finished with value: 0.6738156315579044 and parameters: {'C': 0.013880121949175692, 'l1_ratio': 0.7004095425010929}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,001] Trial 58 finished with value: 0.6724123451622731 and parameters: {'C': 0.01191896338918425, 'l1_ratio': 0.4289631672907591}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,008] Trial 59 finished with value: 0.6724859479254301 and parameters: {'C': 0.010514503476344412, 'l1_ratio': 0.3854660534254499}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,037] Trial 60 finished with value: 0.6718324065476053 and parameters: {'C': 0.01413724001283357, 'l1_ratio': 0.4035853924237449}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,060] Trial 61 finished with value: 0.672102784261429 and parameters: {'C': 0.011867684628634799, 'l1_ratio': 0.38415170174934476}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,117] Trial 65 finished with value: 0.671725946064948 and parameters: {'C': 0.011911926359058049, 'l1_ratio': 0.30750654805780675}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,134] Trial 62 finished with value: 0.6718860046583631 and parameters: {'C': 0.012094013942151358, 'l1_ratio': 0.3564802533675046}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,141] Trial 63 finished with value: 0.6717623062368216 and parameters: {'C': 0.012385736145740185, 'l1_ratio': 0.3340826032563998}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,192] Trial 66 finished with value: 0.6725608142747477 and parameters: {'C': 0.009765699432201846, 'l1_ratio': 0.3647687261769451}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,302] Trial 64 finished with value: 0.6726518729915172 and parameters: {'C': 0.011810176342708756, 'l1_ratio': 0.4566674838866793}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,346] Trial 67 finished with value: 0.6720406509515955 and parameters: {'C': 0.011952854247215261, 'l1_ratio': 0.37776942252022766}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,410] Trial 70 finished with value: 0.6734676912841283 and parameters: {'C': 0.007478782847334534, 'l1_ratio': 0.3433290308593301}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,461] Trial 68 finished with value: 0.6726537602280221 and parameters: {'C': 0.13197363437056941, 'l1_ratio': 0.3769019922914159}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,484] Trial 69 finished with value: 0.6727393842164234 and parameters: {'C': 0.13315447294636687, 'l1_ratio': 0.3365891714741808}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,650] Trial 75 finished with value: 0.6736675658382241 and parameters: {'C': 0.0067764979329036894, 'l1_ratio': 0.3211369747032434}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,703] Trial 76 finished with value: 0.6732679177814762 and parameters: {'C': 0.007155437865730864, 'l1_ratio': 0.31284387655552204}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,749] Trial 71 finished with value: 0.6727121712764487 and parameters: {'C': 0.1311278849621022, 'l1_ratio': 0.34402692704857113}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,838] Trial 72 finished with value: 0.6727357798498247 and parameters: {'C': 0.12704007373187828, 'l1_ratio': 0.31891274416730325}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,860] Trial 74 finished with value: 0.6727164232957364 and parameters: {'C': 0.12602351741806228, 'l1_ratio': 0.3255307074451403}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,888] Trial 80 finished with value: 0.6721920684736836 and parameters: {'C': 0.10132453673388608, 'l1_ratio': 0.4842513056051319}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,911] Trial 77 finished with value: 0.6726759191964675 and parameters: {'C': 0.12378342751724267, 'l1_ratio': 0.33810624929512123}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,921] Trial 73 finished with value: 0.6725633355854059 and parameters: {'C': 0.11379649166323502, 'l1_ratio': 0.3570857980626448}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,961] Trial 78 finished with value: 0.6727309775954546 and parameters: {'C': 0.12940247941403274, 'l1_ratio': 0.3287800356230112}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:45,993] Trial 79 finished with value: 0.6724027693751171 and parameters: {'C': 0.12336988180424403, 'l1_ratio': 0.47791936212827757}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:46,089] Trial 84 finished with value: 0.6723268107540998 and parameters: {'C': 0.12972877300610705, 'l1_ratio': 0.5513602232214918}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:46,107] Trial 83 finished with value: 0.6724716868169235 and parameters: {'C': 0.13372268930358125, 'l1_ratio': 0.4836881903515382}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:46,157] Trial 81 finished with value: 0.6725746608251048 and parameters: {'C': 0.14461328157683973, 'l1_ratio': 0.46624286594633213}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:46,207] Trial 86 finished with value: 0.6719212077994825 and parameters: {'C': 0.09885022020753609, 'l1_ratio': 0.6001379936234968}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:46,255] Trial 82 finished with value: 0.6723823100546381 and parameters: {'C': 0.1221055598875747, 'l1_ratio': 0.48336132951148514}. Best is trial 34 with value: 0.6712119006406437.
[I 2026-09-10 16:48:46,323] Trial 87 finished with value: 0.6712009134517001 and parameters: {'C': 0.041502386971368786, 'l1_ratio': 0.5486792695766549}. Best is trial 87 with value: 0.6712009134517001.
[I 2026-09-10 16:48:46,384] Trial 85 finished with value: 0.6723365304246274 and parameters: {'C': 0.11753758657230623, 'l1_ratio': 0.4886378934795215}. Best is trial 87 with value: 0.6712009134517001.
[I 2026-09-10 16:48:46,387] Trial 88 finished with value: 0.6711974080089772 and parameters: {'C': 0.04011110093631792, 'l1_ratio': 0.5525063266595387}. Best is trial 88 with value: 0.6711974080089772.
[I 2026-09-10 16:48:46,444] Trial 89 finished with value: 0.6712003743710719 and parameters: {'C': 0.039999368072141515, 'l1_ratio': 0.5378840647416753}. Best is trial 88 with value: 0.6711974080089772.
[I 2026-09-10 16:48:46,594] Trial 92 finished with value: 0.671196835614297 and parameters: {'C': 0.04015152867790682, 'l1_ratio': 0.5543412899021526}. Best is trial 92 with value: 0.671196835614297.
[I 2026-09-10 16:48:46,694] Trial 91 finished with value: 0.6711947889023604 and parameters: {'C': 0.04158188636516533, 'l1_ratio': 0.5647162888512784}. Best is trial 91 with value: 0.6711947889023604.
[I 2026-09-10 16:48:46,722] Trial 96 finished with value: 0.6712002748713795 and parameters: {'C': 0.03981428686215733, 'l1_ratio': 0.6197279282325323}. Best is trial 91 with value: 0.6711947889023604.
[I 2026-09-10 16:48:46,751] Trial 95 finished with value: 0.6712275118446887 and parameters: {'C': 0.03782946664268088, 'l1_ratio': 0.6123937729222924}. Best is trial 91 with value: 0.6711947889023604.
[I 2026-09-10 16:48:46,773] Trial 90 finished with value: 0.67119363046767 and parameters: {'C': 0.04057749298387878, 'l1_ratio': 0.5739161427582903}. Best is trial 90 with value: 0.67119363046767.
[I 2026-09-10 16:48:46,793] Trial 97 finished with value: 0.6711914052891357 and parameters: {'C': 0.041294039975522015, 'l1_ratio': 0.6278268814682021}. Best is trial 97 with value: 0.6711914052891357.
[I 2026-09-10 16:48:46,798] Trial 93 finished with value: 0.6711962397654156 and parameters: {'C': 0.03966676370805098, 'l1_ratio': 0.5705067694693928}. Best is trial 97 with value: 0.6711914052891357.
[I 2026-09-10 16:48:46,889] Trial 94 finished with value: 0.6712051591124494 and parameters: {'C': 0.0423363566377523, 'l1_ratio': 0.5443669090092705}. Best is trial 97 with value: 0.6711914052891357.
[I 2026-09-10 16:48:46,930] Trial 98 finished with value: 0.6711999863164699 and parameters: {'C': 0.039242001899140365, 'l1_ratio': 0.5969472935663078}. Best is trial 97 with value: 0.6711914052891357.

Best parameters: {'C': 0.06999262582196647, 'l1_ratio': 0.9631118025051034}

[I 2026-09-10 16:49:07,158] Trial 0 finished with value: 0.6926761920611731 and parameters: {'C': 0.0010811417375907763, 'l1_ratio': 0.30744406138832525}. Best is trial 0 with value: 0.6926761920611731.
[I 2026-09-10 16:49:07,214] Trial 15 finished with value: 0.69267166603813 and parameters: {'C': 0.0020302888722363056, 'l1_ratio': 0.8493653223493264}. Best is trial 15 with value: 0.69267166603813.
[I 2026-09-10 16:49:07,227] Trial 14 finished with value: 0.6926799594740888 and parameters: {'C': 0.0012740044305084568, 'l1_ratio': 0.56467002704357}. Best is trial 15 with value: 0.69267166603813.
[I 2026-09-10 16:49:07,555] Trial 16 finished with value: 0.6894573118812557 and parameters: {'C': 0.003413035149092498, 'l1_ratio': 0.6601172958033694}. Best is trial 16 with value: 0.6894573118812557.
[I 2026-09-10 16:49:07,595] Trial 8 finished with value: 0.6771128910385076 and parameters: {'C': 0.012018805528722126, 'l1_ratio': 0.9339167398819938}. Best is trial 8 with value: 0.6771128910385076.
[I 2026-09-10 16:49:07,605] Trial 2 finished with value: 0.6709863708652819 and parameters: {'C': 0.00974895937559936, 'l1_ratio': 0.2949475937675454}. Best is trial 2 with value: 0.6709863708652819.
[I 2026-09-10 16:49:07,630] Trial 4 finished with value: 0.669985615674926 and parameters: {'C': 0.09744960657229114, 'l1_ratio': 0.5124407708670632}. Best is trial 4 with value: 0.669985615674926.
[I 2026-09-10 16:49:07,672] Trial 11 finished with value: 0.670869971525711 and parameters: {'C': 0.2507377816631965, 'l1_ratio': 0.343669879034492}. Best is trial 4 with value: 0.669985615674926.
[I 2026-09-10 16:49:07,831] Trial 12 finished with value: 0.6703320123781219 and parameters: {'C': 0.24619612084173484, 'l1_ratio': 0.9236938517715293}. Best is trial 4 with value: 0.669985615674926.
[I 2026-09-10 16:49:07,836] Trial 1 finished with value: 0.6703187392459771 and parameters: {'C': 0.01196453477506083, 'l1_ratio': 0.23330076589671112}. Best is trial 4 with value: 0.669985615674926.
[I 2026-09-10 16:49:07,875] Trial 17 finished with value: 0.670423569336045 and parameters: {'C': 0.038419966651069164, 'l1_ratio': 0.08774456043070722}. Best is trial 4 with value: 0.669985615674926.
[I 2026-09-10 16:49:07,886] Trial 13 finished with value: 0.6696460550444614 and parameters: {'C': 0.05433537721694851, 'l1_ratio': 0.9496654506976332}. Best is trial 13 with value: 0.6696460550444614.
[I 2026-09-10 16:49:08,064] Trial 9 finished with value: 0.6695858079721191 and parameters: {'C': 0.08447692632068919, 'l1_ratio': 0.6831409640559245}. Best is trial 9 with value: 0.6695858079721191.
[I 2026-09-10 16:49:08,124] Trial 10 finished with value: 0.6706253001791368 and parameters: {'C': 0.16072704038090124, 'l1_ratio': 0.36468360227929186}. Best is trial 9 with value: 0.6695858079721191.
[I 2026-09-10 16:49:08,178] Trial 5 finished with value: 0.6711726640753013 and parameters: {'C': 0.39794459531606863, 'l1_ratio': 0.13989155295840694}. Best is trial 9 with value: 0.6695858079721191.
[I 2026-09-10 16:49:08,227] Trial 19 finished with value: 0.6702891811339693 and parameters: {'C': 0.038186598028122416, 'l1_ratio': 0.11722411117039089}. Best is trial 9 with value: 0.6695858079721191.
[I 2026-09-10 16:49:08,229] Trial 22 finished with value: 0.6703722647267887 and parameters: {'C': 0.06789075344249071, 'l1_ratio': 0.20479399458184633}. Best is trial 9 with value: 0.6695858079721191.
[I 2026-09-10 16:49:08,301] Trial 23 finished with value: 0.6701458266628394 and parameters: {'C': 0.04006498263060067, 'l1_ratio': 0.15870593883955653}. Best is trial 9 with value: 0.6695858079721191.
[I 2026-09-10 16:49:08,348] Trial 20 finished with value: 0.6708159056317018 and parameters: {'C': 0.2396183531154141, 'l1_ratio': 0.3830148627309453}. Best is trial 9 with value: 0.6695858079721191.
[I 2026-09-10 16:49:08,479] Trial 21 finished with value: 0.6694459014865959 and parameters: {'C': 0.04962845130504973, 'l1_ratio': 0.6740336585313459}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:08,839] Trial 3 finished with value: 0.6712851999251012 and parameters: {'C': 0.9618177760458919, 'l1_ratio': 0.1231135138009195}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:09,028] Trial 31 finished with value: 0.6710275069911475 and parameters: {'C': 0.770132979327722, 'l1_ratio': 0.7565136915138442}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:09,090] Trial 18 finished with value: 0.6712573908190709 and parameters: {'C': 1.5782070538827362, 'l1_ratio': 0.4122974194122422}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:09,523] Trial 33 finished with value: 0.6712038180653142 and parameters: {'C': 1.7502874829681911, 'l1_ratio': 0.7793984922690701}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:09,648] Trial 38 finished with value: 0.6713713899974543 and parameters: {'C': 0.02137559993808649, 'l1_ratio': 0.7447918437731441}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:09,851] Trial 30 finished with value: 0.6712469691891849 and parameters: {'C': 2.3906780413992124, 'l1_ratio': 0.7614055656220138}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:10,092] Trial 28 finished with value: 0.6712473763376805 and parameters: {'C': 2.2480614433241772, 'l1_ratio': 0.7040351547081181}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:10,185] Trial 32 finished with value: 0.6712548571529153 and parameters: {'C': 2.5780075066800183, 'l1_ratio': 0.7593867274241972}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:10,280] Trial 26 finished with value: 0.6712696276544766 and parameters: {'C': 2.683478825667718, 'l1_ratio': 0.665396507269922}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:10,369] Trial 35 finished with value: 0.6712216180428091 and parameters: {'C': 1.8661441129072234, 'l1_ratio': 0.72773856572308}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:10,505] Trial 43 finished with value: 0.6883218744957756 and parameters: {'C': 0.005362124643212253, 'l1_ratio': 0.9898207954230139}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:10,624] Trial 37 finished with value: 0.6712289393962511 and parameters: {'C': 1.9514404613154497, 'l1_ratio': 0.7181579841843528}. Best is trial 21 with value: 0.6694459014865959.
[I 2026-09-10 16:49:10,794] Trial 41 finished with value: 0.6694058719712127 and parameters: {'C': 0.09632718889242015, 'l1_ratio': 0.9992933731388454}. Best is trial 41 with value: 0.6694058719712127.
[I 2026-09-10 16:49:10,879] Trial 44 finished with value: 0.6693708798570446 and parameters: {'C': 0.08359021568036779, 'l1_ratio': 0.9861145615586444}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:10,930] Trial 42 finished with value: 0.6693954700327434 and parameters: {'C': 0.0925686514758231, 'l1_ratio': 0.9889396045470229}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,009] Trial 29 finished with value: 0.6712733835472939 and parameters: {'C': 3.086993727176783, 'l1_ratio': 0.7421372727265344}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,034] Trial 27 finished with value: 0.6713067256165086 and parameters: {'C': 4.617888936148254, 'l1_ratio': 0.6617822058284638}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,151] Trial 7 finished with value: 0.6713262412125648 and parameters: {'C': 9.260575794895836, 'l1_ratio': 0.888348995105587}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,383] Trial 34 finished with value: 0.671304340852736 and parameters: {'C': 4.972801541020671, 'l1_ratio': 0.7591197149689701}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,458] Trial 49 finished with value: 0.6723245588765414 and parameters: {'C': 0.01984959511687053, 'l1_ratio': 0.8529150796670314}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,553] Trial 6 finished with value: 0.6713469538341948 and parameters: {'C': 6.185847275868046, 'l1_ratio': 0.1792150972345974}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,576] Trial 52 finished with value: 0.6730318744915057 and parameters: {'C': 0.017413759271182452, 'l1_ratio': 0.8411761885015309}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,713] Trial 51 finished with value: 0.6719316401755677 and parameters: {'C': 0.020956094162402607, 'l1_ratio': 0.83336104096846}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,837] Trial 53 finished with value: 0.6697622122288958 and parameters: {'C': 0.12470969375888287, 'l1_ratio': 0.8459254212904626}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,858] Trial 36 finished with value: 0.6712986255114164 and parameters: {'C': 4.423713444927391, 'l1_ratio': 0.745796682298442}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:11,971] Trial 54 finished with value: 0.6722913627436256 and parameters: {'C': 0.019824990183216037, 'l1_ratio': 0.8465397879831795}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:12,178] Trial 56 finished with value: 0.6694460159228001 and parameters: {'C': 0.10321576078155557, 'l1_ratio': 0.9989765843346797}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:12,244] Trial 57 finished with value: 0.6701811174543209 and parameters: {'C': 0.1331262168772994, 'l1_ratio': 0.5739856439252871}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:12,284] Trial 40 finished with value: 0.6712882339050641 and parameters: {'C': 4.826103925677461, 'l1_ratio': 0.9862887460824149}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:12,432] Trial 58 finished with value: 0.6695443687233762 and parameters: {'C': 0.11833967771286939, 'l1_ratio': 0.9999988020281819}. Best is trial 44 with value: 0.6693708798570446.
[I 2026-09-10 16:49:12,437] Trial 60 finished with value: 0.6693690434698583 and parameters: {'C': 0.08283049836516675, 'l1_ratio': 0.9898215924740387}. Best is trial 60 with value: 0.6693690434698583.
[I 2026-09-10 16:49:12,494] Trial 59 finished with value: 0.6693668813091819 and parameters: {'C': 0.08220837281503536, 'l1_ratio': 0.998116049850261}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:12,701] Trial 61 finished with value: 0.6693701051603949 and parameters: {'C': 0.08457253536835446, 'l1_ratio': 0.9978122527986055}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:12,892] Trial 62 finished with value: 0.6706389280252468 and parameters: {'C': 0.3980659380267303, 'l1_ratio': 0.9893900124910656}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:12,945] Trial 63 finished with value: 0.6707274738641154 and parameters: {'C': 0.45285825182395906, 'l1_ratio': 0.9742238061049139}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:12,980] Trial 55 finished with value: 0.6712799404916164 and parameters: {'C': 0.502626785487946, 'l1_ratio': 0.021066412706615245}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,032] Trial 66 finished with value: 0.670784663732459 and parameters: {'C': 0.47483941468193946, 'l1_ratio': 0.9108347606163152}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,071] Trial 64 finished with value: 0.6706871452925 and parameters: {'C': 0.3971161610466858, 'l1_ratio': 0.909637177074999}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,170] Trial 67 finished with value: 0.6707849727572218 and parameters: {'C': 0.4718372513453962, 'l1_ratio': 0.9040785413974979}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,283] Trial 24 finished with value: 0.6713560712450138 and parameters: {'C': 7.092230817723557, 'l1_ratio': 0.030869362118667476}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,455] Trial 65 finished with value: 0.6706664228289229 and parameters: {'C': 0.38129813493092607, 'l1_ratio': 0.9029102384573711}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,464] Trial 68 finished with value: 0.6705899797362683 and parameters: {'C': 0.34497570662411453, 'l1_ratio': 0.9183171619710232}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,491] Trial 39 finished with value: 0.6713350350091323 and parameters: {'C': 9.683022123391664, 'l1_ratio': 0.6816892442909279}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,541] Trial 72 finished with value: 0.6700785791074206 and parameters: {'C': 0.1815207474465415, 'l1_ratio': 0.8957437219854596}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,619] Trial 69 finished with value: 0.6701296876256895 and parameters: {'C': 0.19399246567659148, 'l1_ratio': 0.9118017594561063}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,640] Trial 70 finished with value: 0.670100622298221 and parameters: {'C': 0.18892821041502397, 'l1_ratio': 0.9143292962756064}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,766] Trial 71 finished with value: 0.6701259354833098 and parameters: {'C': 0.19369914664947396, 'l1_ratio': 0.9141960195448903}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,837] Trial 73 finished with value: 0.6700250341942404 and parameters: {'C': 0.18210925012680065, 'l1_ratio': 0.947531957011258}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,924] Trial 75 finished with value: 0.670184978868078 and parameters: {'C': 0.2115940763358567, 'l1_ratio': 0.9386045705973031}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,950] Trial 74 finished with value: 0.6695667250449445 and parameters: {'C': 0.05644940180499472, 'l1_ratio': 0.9442026828893363}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:13,980] Trial 48 finished with value: 0.6713189442725703 and parameters: {'C': 7.4658204682182046, 'l1_ratio': 0.8571779240374259}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,148] Trial 78 finished with value: 0.6694513468770855 and parameters: {'C': 0.06312714388326415, 'l1_ratio': 0.9521290633453856}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,161] Trial 77 finished with value: 0.6694388475117363 and parameters: {'C': 0.06401993316139214, 'l1_ratio': 0.9489244871879995}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,186] Trial 79 finished with value: 0.6694534885664989 and parameters: {'C': 0.0628761923196879, 'l1_ratio': 0.9507166388766337}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,350] Trial 76 finished with value: 0.6693971597018484 and parameters: {'C': 0.06849192558383653, 'l1_ratio': 0.9457972416606459}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,357] Trial 82 finished with value: 0.6694979390378754 and parameters: {'C': 0.06055985187281461, 'l1_ratio': 0.9621635288906571}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,409] Trial 80 finished with value: 0.6695021588502774 and parameters: {'C': 0.06023420352113366, 'l1_ratio': 0.9602897440915003}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,433] Trial 81 finished with value: 0.6694245295325062 and parameters: {'C': 0.06561415095400043, 'l1_ratio': 0.9534980181444219}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,522] Trial 45 finished with value: 0.6713065653965334 and parameters: {'C': 6.543256562957274, 'l1_ratio': 0.9847460593632144}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,556] Trial 25 finished with value: 0.6713580649548441 and parameters: {'C': 9.762704662990668, 'l1_ratio': 0.025678549072462753}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,573] Trial 84 finished with value: 0.6701561366535159 and parameters: {'C': 0.06734677978041503, 'l1_ratio': 0.2805283104464267}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,631] Trial 85 finished with value: 0.669817038922951 and parameters: {'C': 0.04205589036575423, 'l1_ratio': 0.2643352305378526}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,636] Trial 50 finished with value: 0.6713027163576919 and parameters: {'C': 5.369797858749931, 'l1_ratio': 0.8563614869997263}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,667] Trial 83 finished with value: 0.6693830710475153 and parameters: {'C': 0.07098401703859994, 'l1_ratio': 0.9448838408291702}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,711] Trial 46 finished with value: 0.6713394233838287 and parameters: {'C': 9.29144407416366, 'l1_ratio': 0.5293420087308289}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,724] Trial 86 finished with value: 0.6694853883672925 and parameters: {'C': 0.08673110151383791, 'l1_ratio': 0.8018730446506956}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,777] Trial 89 finished with value: 0.6694641281222865 and parameters: {'C': 0.08555168814117492, 'l1_ratio': 0.815754801239595}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,912] Trial 88 finished with value: 0.6702820549169364 and parameters: {'C': 0.07848900038434613, 'l1_ratio': 0.2787076124120442}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:14,943] Trial 87 finished with value: 0.6694870072675089 and parameters: {'C': 0.08726513840853278, 'l1_ratio': 0.8045930152830968}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:15,083] Trial 92 finished with value: 0.6710930911276024 and parameters: {'C': 0.031064925940751022, 'l1_ratio': 0.9982949808018606}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:15,132] Trial 91 finished with value: 0.6694770288555028 and parameters: {'C': 0.08713194991053677, 'l1_ratio': 0.8141723140187717}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:15,144] Trial 90 finished with value: 0.6705932930204659 and parameters: {'C': 0.03360332836565712, 'l1_ratio': 0.8697888784445589}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:15,212] Trial 93 finished with value: 0.6705089204195582 and parameters: {'C': 0.03373722522244363, 'l1_ratio': 0.800738323799491}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:15,256] Trial 95 finished with value: 0.6708689752959238 and parameters: {'C': 0.02958517095503649, 'l1_ratio': 0.8781012815028172}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:15,342] Trial 96 finished with value: 0.6694161423710335 and parameters: {'C': 0.08501029046597455, 'l1_ratio': 0.8774987583194747}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:15,366] Trial 99 finished with value: 0.6708151030800507 and parameters: {'C': 0.030619649060630447, 'l1_ratio': 0.8871668853402083}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:15,390] Trial 94 finished with value: 0.6694814491811824 and parameters: {'C': 0.08719868673787912, 'l1_ratio': 0.810021556873048}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:15,404] Trial 97 finished with value: 0.6694846361142126 and parameters: {'C': 0.08801554232429375, 'l1_ratio': 0.8130205954975848}. Best is trial 59 with value: 0.6693668813091819.
[I 2026-09-10 16:49:15,429] Trial 47 finished with value: 0.6713419311364073 and parameters: {'C': 9.999448983752073, 'l1_ratio': 0.5037331504040992}. Best is trial 59 with value: 0.6693668813091819.

Best parameters: {'C': 0.08041415106873516, 'l1_ratio': 0.9985816545399101}

[I 2026-09-10 16:49:36,104] Trial 3 finished with value: 0.6926737886916599 and parameters: {'C': 0.0018945756051311372, 'l1_ratio': 0.6786962568425342}. Best is trial 3 with value: 0.6926737886916599.
[I 2026-09-10 16:49:36,193] Trial 4 finished with value: 0.6868874052889163 and parameters: {'C': 0.002500471099705479, 'l1_ratio': 0.3896106806125189}. Best is trial 4 with value: 0.6868874052889163.
[I 2026-09-10 16:49:36,214] Trial 12 finished with value: 0.683436476830532 and parameters: {'C': 0.002316520225437573, 'l1_ratio': 0.2714091733645574}. Best is trial 12 with value: 0.683436476830532.
[I 2026-09-10 16:49:36,290] Trial 5 finished with value: 0.6867177783208841 and parameters: {'C': 0.004976518294649024, 'l1_ratio': 0.8072208460688876}. Best is trial 12 with value: 0.683436476830532.
[I 2026-09-10 16:49:36,363] Trial 9 finished with value: 0.670358613040257 and parameters: {'C': 0.007329899343364633, 'l1_ratio': 0.11249080030501113}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:36,377] Trial 11 finished with value: 0.6777190183747483 and parameters: {'C': 0.01145426673595999, 'l1_ratio': 0.934983445421013}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:36,422] Trial 15 finished with value: 0.6706758355513871 and parameters: {'C': 0.02470505537340313, 'l1_ratio': 0.010075122436931871}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:36,517] Trial 7 finished with value: 0.6744038327432686 and parameters: {'C': 0.011332833647054757, 'l1_ratio': 0.6523639259596253}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:36,603] Trial 1 finished with value: 0.6705446788436306 and parameters: {'C': 0.02127238309163813, 'l1_ratio': 0.538888096182431}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:36,618] Trial 2 finished with value: 0.6709113661507933 and parameters: {'C': 0.13034859802521326, 'l1_ratio': 0.11387161550799574}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:36,690] Trial 8 finished with value: 0.670465516758582 and parameters: {'C': 0.15446536639878714, 'l1_ratio': 0.45693966479967885}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:36,693] Trial 6 finished with value: 0.6703746138812948 and parameters: {'C': 0.13667810925310686, 'l1_ratio': 0.45657160959624354}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:36,782] Trial 18 finished with value: 0.6711294401023387 and parameters: {'C': 0.014425778286530308, 'l1_ratio': 0.46996866303797424}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:36,830] Trial 14 finished with value: 0.6710588121615417 and parameters: {'C': 0.44591670879635464, 'l1_ratio': 0.3465719945833967}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:36,975] Trial 10 finished with value: 0.6709966988473601 and parameters: {'C': 0.4305601047068957, 'l1_ratio': 0.42888573719663836}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:37,066] Trial 21 finished with value: 0.6709461043976921 and parameters: {'C': 0.7537856560351726, 'l1_ratio': 0.9613524718077688}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:37,156] Trial 22 finished with value: 0.67085977444674 and parameters: {'C': 0.5198805656896174, 'l1_ratio': 0.8288250413258456}. Best is trial 9 with value: 0.670358613040257.
[I 2026-09-10 16:49:37,189] Trial 24 finished with value: 0.6703530762406278 and parameters: {'C': 0.009606833844807984, 'l1_ratio': 0.03246080202999735}. Best is trial 24 with value: 0.6703530762406278.
[I 2026-09-10 16:49:37,219] Trial 23 finished with value: 0.670886081397972 and parameters: {'C': 0.5208419975523565, 'l1_ratio': 0.773173130036389}. Best is trial 24 with value: 0.6703530762406278.
[I 2026-09-10 16:49:37,336] Trial 19 finished with value: 0.6711209051610809 and parameters: {'C': 1.1028865896887416, 'l1_ratio': 0.7645336124246436}. Best is trial 24 with value: 0.6703530762406278.
[I 2026-09-10 16:49:37,778] Trial 34 finished with value: 0.6704478913365721 and parameters: {'C': 0.0673802216701757, 'l1_ratio': 0.1764614340106993}. Best is trial 24 with value: 0.6703530762406278.
[I 2026-09-10 16:49:37,928] Trial 35 finished with value: 0.6703021157923421 and parameters: {'C': 0.05589762918636048, 'l1_ratio': 0.18313723674410137}. Best is trial 35 with value: 0.6703021157923421.
[I 2026-09-10 16:49:37,998] Trial 33 finished with value: 0.6702883663452237 and parameters: {'C': 0.05189205097530903, 'l1_ratio': 0.1712459859524209}. Best is trial 33 with value: 0.6702883663452237.
[I 2026-09-10 16:49:38,086] Trial 13 finished with value: 0.6712740408301114 and parameters: {'C': 2.8713011914694744, 'l1_ratio': 0.6776923874872675}. Best is trial 33 with value: 0.6702883663452237.
[I 2026-09-10 16:49:38,143] Trial 20 finished with value: 0.6711634774233796 and parameters: {'C': 1.4468267036878002, 'l1_ratio': 0.8239625312316654}. Best is trial 33 with value: 0.6702883663452237.
[I 2026-09-10 16:49:38,176] Trial 17 finished with value: 0.671321396425338 and parameters: {'C': 1.4741283260516482, 'l1_ratio': 0.07304540124688585}. Best is trial 33 with value: 0.6702883663452237.
[I 2026-09-10 16:49:38,519] Trial 0 finished with value: 0.6712972453900972 and parameters: {'C': 5.142408773025467, 'l1_ratio': 0.9070448641400526}. Best is trial 33 with value: 0.6702883663452237.
[I 2026-09-10 16:49:38,589] Trial 41 finished with value: 0.6700096645928972 and parameters: {'C': 0.04726177852074846, 'l1_ratio': 0.23296204635554282}. Best is trial 41 with value: 0.6700096645928972.
[I 2026-09-10 16:49:38,755] Trial 39 finished with value: 0.670883763005601 and parameters: {'C': 0.04753722675923065, 'l1_ratio': 0.0031470088019192426}. Best is trial 41 with value: 0.6700096645928972.
[I 2026-09-10 16:49:38,988] Trial 40 finished with value: 0.6708283012177358 and parameters: {'C': 0.05078739552946414, 'l1_ratio': 0.021842460659087043}. Best is trial 41 with value: 0.6700096645928972.
[I 2026-09-10 16:49:39,071] Trial 43 finished with value: 0.6698828225416005 and parameters: {'C': 0.04344335956339799, 'l1_ratio': 0.2514090346275196}. Best is trial 43 with value: 0.6698828225416005.
[I 2026-09-10 16:49:39,145] Trial 42 finished with value: 0.6700199025510039 and parameters: {'C': 0.047105978820138505, 'l1_ratio': 0.22869269985654864}. Best is trial 43 with value: 0.6698828225416005.
[I 2026-09-10 16:49:39,404] Trial 44 finished with value: 0.6701323301616072 and parameters: {'C': 0.06159797633395448, 'l1_ratio': 0.26253370685817573}. Best is trial 43 with value: 0.6698828225416005.
[I 2026-09-10 16:49:39,794] Trial 47 finished with value: 0.6695712028635429 and parameters: {'C': 0.02572409606042714, 'l1_ratio': 0.2844693030701982}. Best is trial 47 with value: 0.6695712028635429.
[I 2026-09-10 16:49:39,925] Trial 48 finished with value: 0.6695740194296748 and parameters: {'C': 0.027980909955477758, 'l1_ratio': 0.28041927503290126}. Best is trial 47 with value: 0.6695712028635429.
[I 2026-09-10 16:49:40,329] Trial 45 finished with value: 0.6709370678214753 and parameters: {'C': 0.22392492282761609, 'l1_ratio': 0.22996689640763457}. Best is trial 47 with value: 0.6695712028635429.
[I 2026-09-10 16:49:40,332] Trial 26 finished with value: 0.6713360422973416 and parameters: {'C': 3.5586992438225216, 'l1_ratio': 0.1723180386942877}. Best is trial 47 with value: 0.6695712028635429.
[I 2026-09-10 16:49:40,369] Trial 49 finished with value: 0.6695747011765312 and parameters: {'C': 0.025255199200011645, 'l1_ratio': 0.2830718799610606}. Best is trial 47 with value: 0.6695712028635429.
[I 2026-09-10 16:49:40,472] Trial 50 finished with value: 0.6695625862596816 and parameters: {'C': 0.026519332935971644, 'l1_ratio': 0.323058304284205}. Best is trial 50 with value: 0.6695625862596816.
[I 2026-09-10 16:49:40,708] Trial 31 finished with value: 0.6713369076989798 and parameters: {'C': 4.132053958689797, 'l1_ratio': 0.20671847373505728}. Best is trial 50 with value: 0.6695625862596816.
[I 2026-09-10 16:49:40,957] Trial 52 finished with value: 0.6698571546135208 and parameters: {'C': 0.020258399164374115, 'l1_ratio': 0.340509802916812}. Best is trial 50 with value: 0.6695625862596816.
[I 2026-09-10 16:49:40,989] Trial 55 finished with value: 0.6768505276706359 and parameters: {'C': 0.004727541196130364, 'l1_ratio': 0.3455932227761652}. Best is trial 50 with value: 0.6695625862596816.
[I 2026-09-10 16:49:41,011] Trial 51 finished with value: 0.6695936739298854 and parameters: {'C': 0.0253776613110124, 'l1_ratio': 0.33517822326524094}. Best is trial 50 with value: 0.6695625862596816.
[I 2026-09-10 16:49:41,027] Trial 53 finished with value: 0.6695620419127964 and parameters: {'C': 0.02694336185584148, 'l1_ratio': 0.3367064863316118}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,055] Trial 54 finished with value: 0.6697103741507375 and parameters: {'C': 0.023579766666400544, 'l1_ratio': 0.36830135581152423}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,158] Trial 58 finished with value: 0.6926799400672233 and parameters: {'C': 0.0011846298638638318, 'l1_ratio': 0.5607516439828286}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,228] Trial 60 finished with value: 0.6926738321397128 and parameters: {'C': 0.0011319191429733715, 'l1_ratio': 0.5364612181578191}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,381] Trial 57 finished with value: 0.6706217732430751 and parameters: {'C': 0.020016319178030203, 'l1_ratio': 0.5340492452555037}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,490] Trial 59 finished with value: 0.6799828260184184 and parameters: {'C': 0.00551052656893941, 'l1_ratio': 0.5316136227045185}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,561] Trial 62 finished with value: 0.6745961343970415 and parameters: {'C': 0.005320218383938211, 'l1_ratio': 0.3003574165317108}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,586] Trial 16 finished with value: 0.6713523289623347 and parameters: {'C': 8.877377167584843, 'l1_ratio': 0.16327117571950878}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,598] Trial 61 finished with value: 0.6760559246394057 and parameters: {'C': 0.007407736591364749, 'l1_ratio': 0.5131682211005241}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,679] Trial 56 finished with value: 0.6697717532453253 and parameters: {'C': 0.021271513921333956, 'l1_ratio': 0.33906855331283253}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,696] Trial 63 finished with value: 0.6760969825279058 and parameters: {'C': 0.005805335013410786, 'l1_ratio': 0.39795394959185326}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:41,871] Trial 28 finished with value: 0.6713440511749291 and parameters: {'C': 6.170388788147619, 'l1_ratio': 0.23131527980251348}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,117] Trial 66 finished with value: 0.6702320525397856 and parameters: {'C': 0.10341194829396184, 'l1_ratio': 0.40745408971998304}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,125] Trial 69 finished with value: 0.6703587553796246 and parameters: {'C': 0.09029097911005757, 'l1_ratio': 0.29216569722895636}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,185] Trial 65 finished with value: 0.6701598525923397 and parameters: {'C': 0.09536802796167321, 'l1_ratio': 0.409948384593665}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,196] Trial 27 finished with value: 0.6713471571024561 and parameters: {'C': 7.3776420945599614, 'l1_ratio': 0.22996217877664243}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,270] Trial 29 finished with value: 0.6713495747687668 and parameters: {'C': 7.9058988775720325, 'l1_ratio': 0.1977479938050219}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,319] Trial 67 finished with value: 0.6703911605633024 and parameters: {'C': 0.09762635251775702, 'l1_ratio': 0.3032500175080908}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,362] Trial 70 finished with value: 0.6704700253389627 and parameters: {'C': 0.10730316351472391, 'l1_ratio': 0.2972268543031117}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,557] Trial 68 finished with value: 0.67038777123993 and parameters: {'C': 0.12590857952215553, 'l1_ratio': 0.4071911130717761}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,599] Trial 25 finished with value: 0.6713423109051673 and parameters: {'C': 7.252485933164249, 'l1_ratio': 0.3278898155011438}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,610] Trial 72 finished with value: 0.669583374945317 and parameters: {'C': 0.03246136905499155, 'l1_ratio': 0.29842539240445676}. Best is trial 53 with value: 0.6695620419127964.
[I 2026-09-10 16:49:42,709] Trial 71 finished with value: 0.6695541166278848 and parameters: {'C': 0.030838624880787334, 'l1_ratio': 0.3091021761142122}. Best is trial 71 with value: 0.6695541166278848.
[I 2026-09-10 16:49:42,724] Trial 32 finished with value: 0.6713496857409751 and parameters: {'C': 8.817011645106763, 'l1_ratio': 0.23003974408162553}. Best is trial 71 with value: 0.6695541166278848.
[I 2026-09-10 16:49:42,770] Trial 73 finished with value: 0.6702672035531798 and parameters: {'C': 0.034004767428325915, 'l1_ratio': 0.10681889955782822}. Best is trial 71 with value: 0.6695541166278848.
[I 2026-09-10 16:49:42,839] Trial 75 finished with value: 0.6702243772619136 and parameters: {'C': 0.030302756056550882, 'l1_ratio': 0.10154428481722835}. Best is trial 71 with value: 0.6695541166278848.
[I 2026-09-10 16:49:42,908] Trial 74 finished with value: 0.6695510903023696 and parameters: {'C': 0.03016360206876852, 'l1_ratio': 0.30872895902423464}. Best is trial 74 with value: 0.6695510903023696.
[I 2026-09-10 16:49:42,929] Trial 76 finished with value: 0.6695257718915595 and parameters: {'C': 0.03079399224239684, 'l1_ratio': 0.37874451846848856}. Best is trial 76 with value: 0.6695257718915595.
[I 2026-09-10 16:49:42,962] Trial 77 finished with value: 0.6695176718437912 and parameters: {'C': 0.03161266912897463, 'l1_ratio': 0.3729782825528185}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:42,976] Trial 36 finished with value: 0.6713527553134917 and parameters: {'C': 5.881061882865361, 'l1_ratio': 0.0646197840044345}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,096] Trial 80 finished with value: 0.670084373261942 and parameters: {'C': 0.03230081894200846, 'l1_ratio': 0.1382409341982216}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,111] Trial 38 finished with value: 0.6713532451316289 and parameters: {'C': 3.9057580678216754, 'l1_ratio': 0.0011961657828661668}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,164] Trial 81 finished with value: 0.6714475489874071 and parameters: {'C': 0.013153934801944697, 'l1_ratio': 0.46659378652081207}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,260] Trial 30 finished with value: 0.6713510044005668 and parameters: {'C': 8.998725990286216, 'l1_ratio': 0.2020339874781522}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,293] Trial 83 finished with value: 0.6698380303145914 and parameters: {'C': 0.013547554599867609, 'l1_ratio': 0.12711963597577894}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,362] Trial 82 finished with value: 0.6701195172282111 and parameters: {'C': 0.033904924993551015, 'l1_ratio': 0.13769023725969703}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,375] Trial 79 finished with value: 0.6701514677755087 and parameters: {'C': 0.034030323528321735, 'l1_ratio': 0.13130198551116273}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,412] Trial 84 finished with value: 0.6715301290354864 and parameters: {'C': 0.012482895469611377, 'l1_ratio': 0.45116465752639806}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,445] Trial 85 finished with value: 0.6698746179228269 and parameters: {'C': 0.012288242071507579, 'l1_ratio': 0.1412856020848037}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,470] Trial 78 finished with value: 0.6695189518006166 and parameters: {'C': 0.03204080337478444, 'l1_ratio': 0.3624765194864152}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,499] Trial 88 finished with value: 0.6708649539349175 and parameters: {'C': 0.014765537211426517, 'l1_ratio': 0.44026566688589136}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,525] Trial 86 finished with value: 0.6711268818413466 and parameters: {'C': 0.014480932881997387, 'l1_ratio': 0.4714791641932815}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,576] Trial 87 finished with value: 0.6707049077288106 and parameters: {'C': 0.016675978296579817, 'l1_ratio': 0.4639741742073572}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,678] Trial 89 finished with value: 0.6705500854462999 and parameters: {'C': 0.01775820554608025, 'l1_ratio': 0.45097461350065776}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,713] Trial 91 finished with value: 0.6706768828044695 and parameters: {'C': 0.015818647535579912, 'l1_ratio': 0.43329749895874087}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,807] Trial 90 finished with value: 0.6711529172174624 and parameters: {'C': 0.01419972340603109, 'l1_ratio': 0.46566107955807}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,845] Trial 37 finished with value: 0.6713578609769877 and parameters: {'C': 9.270531262007081, 'l1_ratio': 0.024544142003629133}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,874] Trial 92 finished with value: 0.6703487243334774 and parameters: {'C': 0.017247356357383843, 'l1_ratio': 0.36927028108253684}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,897] Trial 93 finished with value: 0.6705847803861364 and parameters: {'C': 0.01681174809867777, 'l1_ratio': 0.43754804042977025}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:43,925] Trial 94 finished with value: 0.6705818680155704 and parameters: {'C': 0.01675400894752668, 'l1_ratio': 0.4350214500450028}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:44,045] Trial 95 finished with value: 0.6704607029055973 and parameters: {'C': 0.01660314359887818, 'l1_ratio': 0.3750038927707304}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:44,063] Trial 96 finished with value: 0.6704908534438496 and parameters: {'C': 0.016064282562735472, 'l1_ratio': 0.3778144913880775}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:44,090] Trial 97 finished with value: 0.6705860261311605 and parameters: {'C': 0.01674145634245479, 'l1_ratio': 0.43603972764640603}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:44,134] Trial 100 finished with value: 0.6700223134567983 and parameters: {'C': 0.017545723077069336, 'l1_ratio': 0.31656661923463225}. Best is trial 77 with value: 0.6695176718437912.
[I 2026-09-10 16:49:44,218] Trial 99 finished with value: 0.6700097495749521 and parameters: {'C': 0.07369066568112566, 'l1_ratio': 0.371728519930407}. Best is trial 77 with value: 0.6695176718437912.

Best parameters: {'C': 0.06111643405282459, 'l1_ratio': 0.7281286356660254}
Scores: [0.5990280579497524, 0.5605102040816327, 0.6567045000855529, 0.6004759238521836, 0.5792553191489361, 0.5666489346809643, 0.5672507167887861, 0.5764192139737991]
Parameters: [{'C': 0.03235284138708342, 'l1_ratio': 0.00011053604464882766}, {'C': 0.016125302529960882, 'l1_ratio': 0.0002552884450807108}, {'C': 0.24743444755863572, 'l1_ratio': 0.9667385149953265}, {'C': 0.02073176357863719, 'l1_ratio': 0.0003489405574088563}, {'C': 0.06998262079013826, 'l1_ratio': 0.0005731264604019856}, {'C': 0.06999262582196647, 'l1_ratio': 0.9631118025051034}, {'C': 0.08041415106873516, 'l1_ratio': 0.9985816545399101}, {'C': 0.06111643405282459, 'l1_ratio': 0.7281286356660254}]
Mean roc-auc: 0.5882866088202009

Best parameters: {'C': 0.09750681941092068, 'l1_ratio': 0.9995585639101162}
Scores: [0.6201632129103247, 0.5755102040816327, 0.6403924028973934, 0.6188969764837626, 0.6109742441209407, 0.5641991208668141]
Parameters: [{'C': 0.018106815850875393, 'l1_ratio': 8.967149003731838e-05}, {'C': 0.7266420867985378, 'l1_ratio': 0.8886057619829689}, {'C': 0.12596849532139057, 'l1_ratio': 0.8573565142554178}, {'C': 0.014397512918545604, 'l1_ratio': 6.97621339986504e-05}, {'C': 0.015991938036004197, 'l1_ratio': 0.0003961883721978498}, {'C': 0.09750681941092068, 'l1_ratio': 0.9995585639101162}]
Mean roc-auc: 0.6050226935601447

In [17]:
window_results = []
all_val_true, all_val_proba = [], []
all_test_true, all_test_proba = [], []

for i, (split, params, selected_features) in enumerate(zip(splits, parameters, features)):
    X_train, y_train = split["X_train_raw"], split["y_train"]
    X_val, y_val = split["X_val_raw"], split["y_val"]
    X_test, y_test = split["X_test_raw"], split["y_test"]

    X_train = X_train[selected_features]
    X_val = X_val[selected_features]
    X_test = X_test[selected_features]

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled = scaler.transform(X_val)
    X_test_scaled = scaler.transform(X_test)

    X_train_scaled = pd.DataFrame(X_train_scaled, columns=selected_features)
    X_val_scaled = pd.DataFrame(X_val_scaled, columns=selected_features)
    X_test_scaled = pd.DataFrame(X_test_scaled, columns=selected_features)

    selector = VarianceThreshold(threshold=0.01)
    X_train_sel = selector.fit_transform(X_train_scaled)
    X_val_sel = selector.transform(X_val_scaled)
    X_test_sel = selector.transform(X_test_scaled)

    model = LogisticRegression(C=params['C'], l1_ratio=params['l1_ratio'], solver='saga', max_iter=5000)
    model.fit(X_train_sel, y_train)

    val_proba = model.predict_proba(X_val_sel)[:, 1]
    test_proba = model.predict_proba(X_test_sel)[:, 1]

    window_results.append({
        "window": i,
        "n_val": len(y_val),
        "n_test": len(y_test),
        "val_logloss": log_loss(y_val, val_proba),
        "test_logloss": log_loss(y_test, test_proba),
        "test_acc": accuracy_score(y_test, (test_proba > 0.5).astype(int)),
    })

    all_val_true.append(y_val); all_val_proba.append(val_proba)
    all_test_true.append(y_test); all_test_proba.append(test_proba)

# --- Pool everything: concatenate, don't average ---
# Concatenating before scoring naturally weights each window by its
# sample count. Window 6 (252 matches) counts 252x, Window 2 (32) counts
# 32x — no manual weighting needed, unlike averaging six per-window scores.

pooled_val_true = np.concatenate(all_val_true)
pooled_val_proba = np.concatenate(all_val_proba)
pooled_test_true = np.concatenate(all_test_true)
pooled_test_proba = np.concatenate(all_test_proba)

pooled_test_logloss = log_loss(pooled_test_true, pooled_test_proba)
pooled_test_brier = brier_score_loss(pooled_test_true, pooled_test_proba)
pooled_test_acc = accuracy_score(pooled_test_true, (pooled_test_proba > 0.5).astype(int))

print(f"Pooled test log-loss: {pooled_test_logloss:.4f}")
print(f"Pooled test Brier:    {pooled_test_brier:.4f}")
print(f"Pooled test accuracy: {pooled_test_acc:.4f}  (n={len(pooled_test_true)})")

for r in window_results:
    print(r)


# --- Bootstrap CI, so you can tell if an iteration actually moved the needle ---

def bootstrap_logloss_ci(y_true, y_proba, n_boot=2000, ci=0.95, seed=0):
    rng = np.random.default_rng(seed)
    y_true = np.asarray(y_true)
    y_proba = np.asarray(y_proba)
    n = len(y_true)
    scores = np.empty(n_boot)
    for i in range(n_boot):
        idx = rng.integers(0, n, n)
        scores[i] = log_loss(y_true[idx], y_proba[idx])
    lo, hi = np.percentile(scores, [(1 - ci) / 2 * 100, (1 + ci) / 2 * 100])
    return scores.mean(), lo, hi


mean_ll, lo, hi = bootstrap_logloss_ci(pooled_test_true, pooled_test_proba)
print(f"Pooled log-loss: {mean_ll:.4f}  95% CI [{lo:.4f}, {hi:.4f}]")

Pooled test log-loss: 0.6849
Pooled test Brier:    0.2446
Pooled test accuracy: 0.6128  (n=656)
{'window': 0, 'n_val': 297, 'n_test': 102, 'val_logloss': 0.6160098953902314, 'test_logloss': 0.7929781539838279, 'test_acc': 0.5588235294117647}
{'window': 1, 'n_val': 198, 'n_test': 48, 'val_logloss': 0.7179088768504266, 'test_logloss': 0.6573506830226618, 'test_acc': 0.5625}
{'window': 2, 'n_val': 375, 'n_test': 72, 'val_logloss': 0.629971975384221, 'test_logloss': 0.6798559962275534, 'test_acc': 0.5833333333333334}
{'window': 3, 'n_val': 378, 'n_test': 102, 'val_logloss': 0.6658972156711366, 'test_logloss': 0.6430747700385498, 'test_acc': 0.6274509803921569}
{'window': 4, 'n_val': 378, 'n_test': 72, 'val_logloss': 0.659403409527448, 'test_logloss': 0.6229529444217415, 'test_acc': 0.7916666666666666}
{'window': 5, 'n_val': 378, 'n_test': 56, 'val_logloss': 0.6831301190908927, 'test_logloss': 0.6771481048969203, 'test_acc': 0.5535714285714286}
{'window': 6, 'n_val': 434, 'n_test': 24, 'val_logloss': 0.6824039973517271, 'test_logloss': 0.6321759918264271, 'test_acc': 0.7083333333333334}
{'window': 7, 'n_val': 458, 'n_test': 180, 'val_logloss': 0.679863106436259, 'test_logloss': 0.6908037615457459, 'test_acc': 0.5944444444444444}
Pooled log-loss: 0.6849  95% CI [0.6593, 0.7116]

Pooled test log-loss: 0.6991
Pooled test Brier:    0.2505
Pooled test accuracy: 0.6305  (n=452)
{'window': 0, 'n_val': 297, 'n_test': 102, 'val_logloss': 0.6110449366927905, 'test_logloss': 0.7904254984225982, 'test_acc': 0.5588235294117647}
{'window': 1, 'n_val': 198, 'n_test': 48, 'val_logloss': 0.737514643554363, 'test_logloss': 0.747652112307672, 'test_acc': 0.4583333333333333}
{'window': 2, 'n_val': 375, 'n_test': 72, 'val_logloss': 0.6548906787828987, 'test_logloss': 0.7226250820050232, 'test_acc': 0.7083333333333334}
{'window': 3, 'n_val': 378, 'n_test': 102, 'val_logloss': 0.6519088207608126, 'test_logloss': 0.6378737833967578, 'test_acc': 0.6764705882352942}
{'window': 4, 'n_val': 378, 'n_test': 72, 'val_logloss': 0.651855945000742, 'test_logloss': 0.6233010739981247, 'test_acc': 0.75}
{'window': 5, 'n_val': 378, 'n_test': 56, 'val_logloss': 0.6876066836409673, 'test_logloss': 0.6700529918128618, 'test_acc': 0.5714285714285714}
Pooled log-loss: 0.6993  95% CI [0.6632, 0.7360]

In [18]:
parameters

[{'C': 0.03235284138708342, 'l1_ratio': 0.00011053604464882766},
 {'C': 0.016125302529960882, 'l1_ratio': 0.0002552884450807108},
 {'C': 0.24743444755863572, 'l1_ratio': 0.9667385149953265},
 {'C': 0.02073176357863719, 'l1_ratio': 0.0003489405574088563},
 {'C': 0.06998262079013826, 'l1_ratio': 0.0005731264604019856},
 {'C': 0.06999262582196647, 'l1_ratio': 0.9631118025051034},
 {'C': 0.08041415106873516, 'l1_ratio': 0.9985816545399101},
 {'C': 0.06111643405282459, 'l1_ratio': 0.7281286356660254}]

In [19]:
pd.DataFrame(model.coef_[0], index=selector.get_feature_names_out(), columns=["Coefficient"]).sort_values(by="Coefficient", key=abs, ascending=False)

                                                    Coefficient
delta_match_patch_win_rate                             0.189017
delta_match_patch_win_rate_4                          -0.180085
delta_match_score_delta_sum_4                          0.168576
delta_map_specific_score_delta_avg_4                   0.136283
delta_player_map_stats_specific_clutch_1v1_vari...     0.122370
delta_player_map_stats_specific_average_damage_...     0.110320
delta_match_patch_played_ratio                        -0.110169
delta_player_map_stats_specific_clutch_1v3_medi...     0.105740
delta_player_map_stats_specific_three_kills_median     0.087448
delta_player_map_stats_specific_average_combat_...     0.061605
delta_map_specific_score_delta_sum_4                   0.054852
delta_player_map_stats_specific_first_kills_var...     0.033282
delta_player_map_stats_specific_first_kills_var...    -0.009271
delta_player_map_stats_specific_clutch_1v4_medi...     0.005877
delta_match_patch_played                              -0.002028
delta_player_map_stats_specific_clutch_1v1_medi...    -0.000714
delta_player_map_stats_specific_four_kills_median      0.000000
delta_map_specific_score_delta_sum_2                   0.000000
delta_player_map_stats_specific_clutch_1v3_medi...     0.000000
delta_player_map_stats_specific_deaths_median_2        0.000000
delta_player_map_stats_specific_clutch_1v4_medi...     0.000000
delta_match_patch_score_delta_avg_6                    0.000000
delta_map_score_delta_avg_2                            0.000000

In [20]:
np.array(selected_features)[selector.get_support()]

array(['delta_player_map_stats_specific_clutch_1v4_median_2',
       'delta_player_map_stats_specific_four_kills_median',
       'delta_player_map_stats_specific_average_damage_per_round_median_2',
       'delta_player_map_stats_specific_clutch_1v1_median_6',
       'delta_map_specific_score_delta_sum_2',
       'delta_match_patch_win_rate_4',
       'delta_map_specific_score_delta_sum_4',
       'delta_player_map_stats_specific_clutch_1v3_median_4',
       'delta_player_map_stats_specific_average_combat_score_variance_log1p_2',
       'delta_player_map_stats_specific_clutch_1v4_median_4',
       'delta_match_patch_played',
       'delta_player_map_stats_specific_three_kills_median',
       'delta_player_map_stats_specific_deaths_median_2',
       'delta_map_specific_score_delta_avg_4',
       'delta_player_map_stats_specific_first_kills_variance_log1p',
       'delta_match_patch_played_ratio',
       'delta_match_patch_score_delta_avg_6',
       'delta_match_patch_win_rate',
       'delta_player_map_stats_specific_first_kills_variance_log1p_4',
       'delta_player_map_stats_specific_clutch_1v1_variance_log1p',
       'delta_map_score_delta_avg_2', 'delta_match_score_delta_sum_4',
       'delta_player_map_stats_specific_clutch_1v3_median_6'],
      dtype='<U69')

In [21]:
split.keys()

dict_keys(['X_train_raw', 'y_train', 'X_val_raw', 'y_val', 'X_test_raw', 'y_test'])

In [22]:
import numpy as np
import pandas as pd
from sklearn.metrics import log_loss, brier_score_loss, accuracy_score

window_results = []
all_val_true, all_val_proba = [], []
all_test_true, all_test_proba = [], []

match_rows = []      # Layer 1: one row per match (val set)
feature_rows = []    # Layer 2: one row per match x feature (val set)

for i, (split, params, selected_features) in enumerate(zip(splits, parameters, features)):
    X_train, y_train = split["X_train_raw"], split["y_train"]
    X_val, y_val = split["X_val_raw"], split["y_val"]
    X_test, y_test = split["X_test_raw"], split["y_test"]

    X_train = X_train[selected_features]
    X_val = X_val[selected_features]
    X_test = X_test[selected_features]

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled = scaler.transform(X_val)
    X_test_scaled = scaler.transform(X_test)

    X_train_scaled = pd.DataFrame(X_train_scaled, columns=selected_features)
    X_val_scaled = pd.DataFrame(X_val_scaled, columns=selected_features)
    X_test_scaled = pd.DataFrame(X_test_scaled, columns=selected_features)

    selector = VarianceThreshold(threshold=0.01)
    X_train_sel = selector.fit_transform(X_train_scaled)
    X_val_sel = selector.transform(X_val_scaled)
    X_test_sel = selector.transform(X_test_scaled)

    # names of columns that survived VarianceThreshold, in order
    surviving_features = np.array(selected_features)[selector.get_support()]

    model = LogisticRegression(C=params['C'], l1_ratio=params['l1_ratio'], solver='saga', max_iter=5000)
    model.fit(X_train_sel, y_train)

    val_proba = model.predict_proba(X_val_sel)[:, 1]
    test_proba = model.predict_proba(X_test_sel)[:, 1]

    window_results.append({
        "window": i,
        "n_val": len(y_val),
        "n_test": len(y_test),
        "val_logloss": log_loss(y_val, val_proba),
        "test_logloss": log_loss(y_test, test_proba),
        "test_acc": accuracy_score(y_test, (test_proba > 0.5).astype(int)),
    })

    all_val_true.append(y_val); all_val_proba.append(val_proba)
    all_test_true.append(y_test); all_test_proba.append(test_proba)

    # ---------- Layer 1: match-level results (VAL) ----------
    vlr_match_ids = np.asarray(split['X_val_raw']["vlr_match_id"])  # adjust key to your actual field
    # match_ids = split.get("match_id_val", np.arange(len(y_val)))  # adjust key to your actual field
    y_val_arr = np.asarray(y_val)
    pred_label = (val_proba > 0.5).astype(int)
    eps = 1e-9
    ll_contrib = -(y_val_arr * np.log(np.clip(val_proba, eps, 1 - eps)) +
                   (1 - y_val_arr) * np.log(np.clip(1 - val_proba, eps, 1 - eps)))

    window_match_df = pd.DataFrame({
        "vlr_match_id": vlr_match_ids,
        "window": i,
        "y_true": y_val_arr,
        "y_pred_proba": val_proba,
        "pred_label": pred_label,
        "correct": pred_label == y_val_arr,
        "confidence": np.abs(val_proba - 0.5) * 2,
        "log_loss_contribution": ll_contrib,
        "p_favorite": np.maximum(val_proba, 1 - val_proba),
    })
    window_match_df["favorite_won"] = np.where(
        val_proba > 0.5, window_match_df["y_true"] == 1, window_match_df["y_true"] == 0
    )
    # join metadata here if it lives elsewhere, e.g.:
    # window_match_df = window_match_df.merge(metadata_df, on="match_id", how="left")
    match_rows.append(window_match_df)

    # ---------- Layer 2: feature-level SHAP (VAL) ----------
    # Manual linear-SHAP-style attribution: coef * (x - train_mean), matching
    # your existing manual approach from the deployed SHAP implementation.
    train_mean = X_train_sel.mean(axis=0)
    coefs = model.coef_[0]
    shap_matrix = (np.asarray(X_val_sel) - train_mean) * coefs  # shape (n_val, n_features)

    n_val_rows, n_feats = shap_matrix.shape
    window_feature_df = pd.DataFrame({
        "vlr_match_id": np.repeat(vlr_match_ids, n_feats),
        "window": i,
        "feature_name": np.tile(surviving_features, n_val_rows),
        "feature_value_raw": np.asarray(X_val[surviving_features]).flatten(),
        "feature_value_scaled": np.asarray(X_val_sel).flatten(),
        "shap_value": shap_matrix.flatten(),
    })
    feature_rows.append(window_feature_df)

# ---------- Assemble the two output tables ----------
results_df = pd.concat(match_rows, ignore_index=True)
shap_df = pd.concat(feature_rows, ignore_index=True)

# --- Pool test metrics: unchanged, still the integrity check ---
pooled_val_true = np.concatenate(all_val_true)
pooled_val_proba = np.concatenate(all_val_proba)
pooled_test_true = np.concatenate(all_test_true)
pooled_test_proba = np.concatenate(all_test_proba)

pooled_test_logloss = log_loss(pooled_test_true, pooled_test_proba)
pooled_test_brier = brier_score_loss(pooled_test_true, pooled_test_proba)
pooled_test_acc = accuracy_score(pooled_test_true, (pooled_test_proba > 0.5).astype(int))

print(f"Pooled test log-loss: {pooled_test_logloss:.4f}")
print(f"Pooled test Brier:    {pooled_test_brier:.4f}")
print(f"Pooled test accuracy: {pooled_test_acc:.4f}  (n={len(pooled_test_true)})")

for r in window_results:
    print(r)

Pooled test log-loss: 0.6849
Pooled test Brier:    0.2446
Pooled test accuracy: 0.6128  (n=656)
{'window': 0, 'n_val': 297, 'n_test': 102, 'val_logloss': 0.6160102349147357, 'test_logloss': 0.7929828396414882, 'test_acc': 0.5588235294117647}
{'window': 1, 'n_val': 198, 'n_test': 48, 'val_logloss': 0.7179077884116832, 'test_logloss': 0.6573511065853541, 'test_acc': 0.5625}
{'window': 2, 'n_val': 375, 'n_test': 72, 'val_logloss': 0.6299707067282205, 'test_logloss': 0.6798618127818842, 'test_acc': 0.5833333333333334}
{'window': 3, 'n_val': 378, 'n_test': 102, 'val_logloss': 0.6658955900280408, 'test_logloss': 0.643067804921362, 'test_acc': 0.6274509803921569}
{'window': 4, 'n_val': 378, 'n_test': 72, 'val_logloss': 0.6593989280981094, 'test_logloss': 0.6229479237048646, 'test_acc': 0.7916666666666666}
{'window': 5, 'n_val': 378, 'n_test': 56, 'val_logloss': 0.683129475788515, 'test_logloss': 0.6771465448455665, 'test_acc': 0.5535714285714286}
{'window': 6, 'n_val': 434, 'n_test': 24, 'val_logloss': 0.6824039569290913, 'test_logloss': 0.6321761568333981, 'test_acc': 0.7083333333333334}
{'window': 7, 'n_val': 458, 'n_test': 180, 'val_logloss': 0.6798630466839722, 'test_logloss': 0.6908036059207221, 'test_acc': 0.5944444444444444}

In [40]:
joblib.dump(model, "model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(selector, "selector.pkl")
joblib.dump(imputer, "imputer.pkl")

X_bg = X_train.reindex(columns=selector.feature_names_in_)
# X_bg = imputer.transform(X_bg)
X_bg = scaler.transform(X_bg)
X_bg = selector.transform(X_bg)

joblib.dump(X_bg.mean(axis=0), "background_mean.npy")
joblib.dump(X_bg.std(axis=0), "background_std.npy")

['background_std.npy']

In [24]:
results_df

,vlr_match_id,window,y_true,y_pred_proba,pred_label,correct,confidence,log_loss_contribution,p_favorite,favorite_won
0,314340.0,0,1,0.677665,1,True,0.355330,0.389102,0.677665,True
1,314341.0,0,1,0.814137,1,True,0.628273,0.205627,0.814137,True
2,314340.0,0,0,0.328668,0,True,0.342664,0.398492,0.671332,True
3,314341.0,0,0,0.190268,0,True,0.619464,0.211052,0.809732,True
4,314340.0,0,1,0.677665,1,True,0.355330,0.389102,0.677665,True
...,...,...,...,...,...,...,...,...,...,...
2891,708424.0,7,1,0.475514,0,False,0.048971,0.743358,0.524486,False
2892,708426.0,7,1,0.570627,1,True,0.141254,0.561019,0.570627,True
2893,708426.0,7,0,0.406876,0,True,0.186247,0.522353,0.593124,True
2894,708427.0,7,0,0.426789,0,True,0.146421,0.556502,0.573211,True
2895,708427.0,7,1,0.550448,1,True,0.100895,0.597024,0.550448,True

### Calibration by confidence bucket — is the model's stated confidence honest?

A well-calibrated model's 0.7-0.8 bucket should see the favorite win ~70-80% of the time. Systematic gaps (e.g. that bucket only wins 60%) tell you the model is overconfident in a specific range — that's a concrete, testable failure mode, not vague "accuracy could be better."

In [25]:
results_df["conf_bucket"] = pd.cut(results_df["p_favorite"], bins=[0.5, 0.6, 0.7, 0.8, 0.9, 1.0])
calib = results_df.groupby("conf_bucket").agg(
    n=("favorite_won", "size"),
    empirical_win_rate=("favorite_won", "mean"),
)
print(calib)

                n  empirical_win_rate
conf_bucket
(0.5, 0.6]   1639            0.542404
(0.6, 0.7]    842            0.602138
(0.7, 0.8]    305            0.727869
(0.8, 0.9]    104            0.798077
(0.9, 1.0]      6            1.000000

### Confident-and-wrong matches — the highest-value failure mode to inspect individually

This is your shortlist for manually pulling up the actual match pages — if several cluster around a shared trait (recent roster change, a specific region, a big seed gap), that's a feature hypothesis forming directly from evidence.

In [26]:
confident_wrong = results_df[(results_df["confidence"] > 0.5) & (~results_df["correct"])].sort_values(
    "log_loss_contribution", ascending=False
)
confident_wrong.head(20)

,vlr_match_id,window,y_true,y_pred_proba,pred_label,correct,confidence,log_loss_contribution,p_favorite,favorite_won,conf_bucket
528,458809.0,2,1,0.102646,0,False,0.794708,2.276467,0.897354,False,"(0.8, 0.9]"
526,458809.0,2,1,0.102646,0,False,0.794708,2.276467,0.897354,False,"(0.8, 0.9]"
525,458809.0,2,0,0.887500,1,False,0.775000,2.184802,0.887500,False,"(0.8, 0.9]"
438,430531.0,1,1,0.114354,0,False,0.771292,2.168458,0.885646,False,"(0.8, 0.9]"
134,353189.0,0,0,0.883777,1,False,0.767554,2.152246,0.883777,False,"(0.8, 0.9]"
441,430531.0,1,0,0.882029,1,False,0.764057,2.137313,0.882029,False,"(0.8, 0.9]"
433,430531.0,1,0,0.882029,1,False,0.764057,2.137313,0.882029,False,"(0.8, 0.9]"
137,353189.0,0,1,0.119219,0,False,0.761562,2.126795,0.880781,False,"(0.8, 0.9]"
132,353189.0,0,1,0.119219,0,False,0.761562,2.126795,0.880781,False,"(0.8, 0.9]"
572,459527.0,2,1,0.146892,0,False,0.706217,1.918061,0.853108,False,"(0.8, 0.9]"
571,459527.0,2,1,0.146892,0,False,0.706217,1.918061,0.853108,False,"(0.8, 0.9]"
570,459527.0,2,0,0.845659,1,False,0.691318,1.868592,0.845659,False,"(0.8, 0.9]"
216,353198.0,0,0,0.836639,1,False,0.673278,1.811794,0.836639,False,"(0.8, 0.9]"
224,353198.0,0,1,0.167342,0,False,0.665316,1.787716,0.832658,False,"(0.8, 0.9]"
217,353198.0,0,1,0.167342,0,False,0.665316,1.787716,0.832658,False,"(0.8, 0.9]"
665,458824.0,2,1,0.168746,0,False,0.662508,1.779361,0.831254,False,"(0.8, 0.9]"
671,458824.0,2,1,0.168746,0,False,0.662508,1.779361,0.831254,False,"(0.8, 0.9]"
667,458824.0,2,0,0.822926,1,False,0.645853,1.731190,0.822926,False,"(0.8, 0.9]"
317,429385.0,1,1,0.184198,0,False,0.631605,1.691746,0.815802,False,"(0.8, 0.9]"
323,429385.0,1,1,0.184198,0,False,0.631605,1.691746,0.815802,False,"(0.8, 0.9]"

In [27]:
for i, vlr_match in enumerate(confident_wrong["vlr_match_id"].unique()):
    print(f"{i + 1}: https://www.vlr.gg/{int(vlr_match)}")

1: https://www.vlr.gg/458809
2: https://www.vlr.gg/430531
3: https://www.vlr.gg/353189
4: https://www.vlr.gg/459527
5: https://www.vlr.gg/353198
6: https://www.vlr.gg/458824
7: https://www.vlr.gg/429385
8: https://www.vlr.gg/473844
9: https://www.vlr.gg/473843
10: https://www.vlr.gg/353179
11: https://www.vlr.gg/353163
12: https://www.vlr.gg/314362
13: https://www.vlr.gg/314350
14: https://www.vlr.gg/365317

### Does performance drift across windows (temporal check)?

A steady trend (getting worse in later windows) suggests meta/roster drift outpacing your features' freshness; a flat pattern says the ceiling is stable over time, not eroding.

In [28]:
window_summary = results_df.groupby("window").agg(
    n=("correct", "size"),
    acc=("correct", "mean"),
    mean_logloss=("log_loss_contribution", "mean"),
)
window_summary

          n       acc  mean_logloss
window
0       297  0.602694      0.616010
1       198  0.560606      0.717908
2       375  0.658667      0.629971
3       378  0.600529      0.665896
4       378  0.579365      0.659399
5       378  0.566138      0.683129
6       434  0.566820      0.682404
7       458  0.576419      0.679863

### SHAP: correct vs. incorrect predictions — which features behave differently on failures

Features with a high ratio are pulling extra weight specifically on matches the model gets wrong — worth asking why. Keep n_windows_selected visible since a feature that only appeared in one window's top-30 has a much smaller, less trustworthy sample behind its number.

In [29]:
merged = shap_df.merge(results_df[["vlr_match_id", "window", "correct", "y_true"]], on=["vlr_match_id", "window"])

shap_compare = merged.groupby(["feature_name", "correct"])["shap_value"].apply(
    lambda s: s.abs().mean()
).unstack("correct").rename(columns={True: "mean_abs_shap_correct", False: "mean_abs_shap_wrong"})

shap_compare["n_windows_selected"] = merged.groupby("feature_name")["window"].nunique()
shap_compare["ratio_wrong_to_correct"] = shap_compare["mean_abs_shap_wrong"] / shap_compare["mean_abs_shap_correct"]
shap_compare.sort_values("ratio_wrong_to_correct", ascending=False)

correct,mean_abs_shap_wrong,mean_abs_shap_correct,n_windows_selected,ratio_wrong_to_correct
feature_name,,,,
delta_player_map_stats_specific_five_kills_variance_log1p_6,0.016663,0.010112,2,1.647915
delta_map_patch_score_delta_avg_2,0.037272,0.028761,1,1.295913
delta_player_map_stats_specific_defuses_median,0.014538,0.011359,4,1.279865
delta_player_map_stats_specific_deaths_variance_log1p_6,0.029649,0.023294,3,1.272824
delta_player_map_stats_specific_clutch_1v1_median_6,0.000135,0.000108,3,1.252121
...,...,...,...,...
delta_player_map_stats_specific_clutch_1v4_median_2,0.000079,0.000224,3,0.354556
delta_player_map_stats_specific_plants_median,0.006259,0.047827,1,0.130877
delta_player_map_stats_specific_clutch_1v4_median_4,0.000000,0.000000,3,NaN
delta_player_map_stats_specific_deaths_median_2,0.000000,0.000000,3,NaN
delta_player_map_stats_specific_four_kills_median,0.000000,0.000000,3,NaN

In [30]:
shap_compare.describe()

correct,mean_abs_shap_wrong,mean_abs_shap_correct,n_windows_selected,ratio_wrong_to_correct
count,70.000000,70.000000,70.000000,67.000000
mean,0.054036,0.058277,2.714286,0.968030
std,0.063899,0.072111,1.858337,0.223738
min,0.000000,0.000000,1.000000,0.130877
25%,0.012720,0.012053,1.000000,0.840365
50%,0.038466,0.039432,2.000000,0.990151
75%,0.057911,0.060628,3.000000,1.077200
max,0.271051,0.349219,8.000000,1.647915

### Does a specific feature actually vary in the slice you think it explains?

If feature_value_raw is nearly constant across this slice, the feature isn't distinguishing these failures regardless of its SHAP weight elsewhere — it's the direct test from the "I think I already have this feature" discussion.

In [31]:
feature_to_check = "delta_map_specific_score_delta_avg_4"  # example
bad_slice_ids = confident_wrong["vlr_match_id"]

check = shap_df[
    (shap_df["feature_name"] == feature_to_check) & (shap_df["vlr_match_id"].isin(bad_slice_ids))
]
check[["vlr_match_id", "feature_value_raw", "shap_value"]].describe()

       vlr_match_id  feature_value_raw  shap_value
count           0.0                0.0         0.0
mean            NaN                NaN         NaN
std             NaN                NaN         NaN
min             NaN                NaN         NaN
25%             NaN                NaN         NaN
50%             NaN                NaN         NaN
75%             NaN                NaN         NaN
max             NaN                NaN         NaN

### Direction-flip check

If mean SHAP is positive-and-favors-the-actual-winner on correct predictions but positive-and-favors-the-loser on incorrect ones, that's evidence of a confound the feature isn't disentangling (e.g. it correlates with team strength most of the time, but misfires under some condition you haven't captured yet — which is your next hypothesis to chase).

In [32]:
sign_check = merged[merged["feature_name"] == feature_to_check].groupby("correct")["shap_value"].mean()
print(sign_check)

correct
False    0.002651
True     0.006301
Name: shap_value, dtype: float64

In [33]:
flip_check = merged[merged["feature_name"] == feature_to_check].groupby("correct")["shap_favored_winner"].agg(["mean", "size"])
print(flip_check)

KeyError: 'Column not found: shap_favored_winner'

In [ ]:
feature_idx = list(surviving_features).index(feature_to_check)
print(model.coef_[0][feature_idx])

0.13923271969230527

In [ ]:
raw_vals = shap_df[shap_df["feature_name"] == feature_to_check]["feature_value_raw"]
print(raw_vals.skew())
print(raw_vals.describe())
print((raw_vals < raw_vals.mean()).mean())  # fraction below the mean

0.011399511307678412
count    753.000000
mean      -0.146746
std        4.359908
min      -13.000000
25%       -3.000000
50%        0.000000
75%        2.750000
max       13.000000
Name: feature_value_raw, dtype: float64
0.4953519256308101